using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;

namespace MapaDyskow {
public sealed class ProfilPlytki {
    public bool Wlaczona {get;set;} public double Przezroczystosc {get;set;} public double Rozmycie {get;set;} public double Zaokraglenie {get;set;}
    public double Rozmiar {get;set;} public double Padding {get;set;} public string Kolor {get;set;} public string TrybKoloru {get;set;}
    public string Obramowanie {get;set;} public string KolorObramowania {get;set;} public double AlfaObramowania {get;set;} public double Grubosc {get;set;}
    public string Szklo {get;set;} public string Refleks {get;set;} public string Ksztalt {get;set;} public bool RamkaMiniatury {get;set;} public double Ikona {get;set;}
    public ProfilPlytki(){Wlaczona=true;Przezroczystosc=72;Rozmycie=20;Zaokraglenie=16;Rozmiar=112;Padding=12;Kolor="#8999AC";TrybKoloru="Automatyczny";Obramowanie="Subtelne";KolorObramowania="#D1DFED";AlfaObramowania=18;Grubosc=1;Szklo="Subtelny";Refleks="Subtelny";Ksztalt="Lekko zaokrąglony";RamkaMiniatury=true;Ikona=80;}
}
public sealed class Wyglad {
    public List<UkladKolumn> Kolumny=new List<UkladKolumn>(); public Dictionary<string,UkladFolderu> UkladyFolderow=new Dictionary<string,UkladFolderu>(StringComparer.OrdinalIgnoreCase); public bool FolderyNaPoczatku=true; public bool PanelSzczegolow=true; public double SzerokoscPanelu=360; public Dictionary<string,bool> SekcjePanelu=new Dictionary<string,bool>();
    public Dictionary<string,string> KluczeMiniatur=new Dictionary<string,string>();
    public double SkalaDuzych {get;set;} public double SkalaKompaktowych {get;set;}
    public bool ProfileZainicjalizowane {get;set;}
    public string Preset {get;set;} public string TrybFolderow {get;set;} public string KolorFolderow {get;set;} public bool OsobneProfile {get;set;}
    public ProfilPlytki Wspolny {get;set;} public Dictionary<string,ProfilPlytki> Profile {get;set;} public Dictionary<string,string> Widoki {get;set;}
    public Dictionary<string,string> KoloryKategorii {get;set;} public Dictionary<string,string> KoloryTagow {get;set;}
    public Wyglad(){SkalaDuzych=100;SkalaKompaktowych=100;Preset="Windows Fluent";TrybFolderow="Systemowy / domyślny";KolorFolderow="#D6A84B";Wspolny=new ProfilPlytki();Profile=new Dictionary<string,ProfilPlytki>();Widoki=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);KoloryKategorii=new Dictionary<string,string>();KoloryTagow=new Dictionary<string,string>();foreach(string typ in new[]{"Folder","Film","Zdjęcie","Dokument","Archiwum","Audio","System"}){Profile[typ]=new ProfilPlytki();KoloryKategorii[typ]=typ=="Film"?"#4D95BB":typ=="Zdjęcie"?"#69A99D":typ=="Archiwum"?"#A78DC5":"#D6A84B";}KoloryTagow["ZGRYW TELEFONU"]="#69A99D";KoloryTagow["BACKUP"]="#A78DC5";KoloryTagow["STARE DANE"]="#BB9D70";}
    public ProfilPlytki Dla(string typ){if(typ=="Arkusz")typ="Dokument";return OsobneProfile&&Profile.ContainsKey(typ)?Profile[typ]:Wspolny;}
}
public sealed class MetadaneKafelka {
    public DateTime? Utworzenie;public int Szerokosc,Wysokosc;public BitmapSource Miniatura;
    public int Klatki,Bitrate;public TimeSpan? Czas;public int Bity,Czestotliwosc,Strony;
}
public static class Kafelki {
    public static void ZmienSciezkiCache(string stara,string nowa){
        using(var baza=new Baza(Program.Indeks,false))foreach(var r in baza.Zapytaj("SELECT sciezka,rozmiar,zmiana FROM pliki WHERE sciezka=? COLLATE NOCASE OR sciezka LIKE ? ESCAPE '^'",nowa,Program.Prefiks(nowa))){
            string sciezka=(string)r[0],przed=OperacjePlikowe.Podmien(sciezka,nowa,stara),sufiks="|"+r[1]+"|"+Convert.ToDouble(r[2]).ToString("R",System.Globalization.CultureInfo.InvariantCulture),klucz=przed+sufiks,oryginal;
            lock(blokada){if(Ustawienia.KluczeMiniatur.TryGetValue(klucz,out oryginal))klucz=oryginal;
            Ustawienia.KluczeMiniatur[sciezka+sufiks]=klucz;}
        }
        try{Zapisz();}catch(IOException){}catch(UnauthorizedAccessException){}
    }
    public static Wyglad Ustawienia=new Wyglad(); public static Func<Wiersz,ContextMenu> MenuElementu;
    static readonly SemaphoreSlim pracownicy=new SemaphoreSlim(2);static readonly object blokada=new object();
    static readonly Dictionary<string,MetadaneKafelka> pamiec=new Dictionary<string,MetadaneKafelka>();
    static readonly Queue<string> kolejnosc=new Queue<string>();
    static int zapisaneMiniatury=-1;
    static bool RezerwujMiniature(string katalog){lock(blokada){if(zapisaneMiniatury<0)zapisaneMiniatury=Directory.EnumerateFiles(katalog,"*.png").Take(5000).Count();if(zapisaneMiniatury>=5000)return false;zapisaneMiniatury++;return true;}}
    public static void Wczytaj(){string sciezka=Path.Combine(Program.Katalog,"wyglad.json");if(File.Exists(sciezka)){try{Ustawienia=Program.Json.Deserialize<Wyglad>(File.ReadAllText(sciezka));Ustawienia.Widoki=new Dictionary<string,string>(Ustawienia.Widoki,StringComparer.OrdinalIgnoreCase);Ustawienia.UkladyFolderow=new Dictionary<string,UkladFolderu>(Ustawienia.UkladyFolderow??new Dictionary<string,UkladFolderu>(),StringComparer.OrdinalIgnoreCase);if(Ustawienia.Kolumny==null)Ustawienia.Kolumny=new List<UkladKolumn>();if(Ustawienia.OsobneProfile)Ustawienia.ProfileZainicjalizowane=true;}catch{Ustawienia=new Wyglad();}}}
    public static void Zapisz(){File.WriteAllText(Path.Combine(Program.Katalog,"wyglad.json"),Program.Json.Serialize(Ustawienia),System.Text.Encoding.UTF8);}
    public static string Kategoria(Wiersz w){if(w.Systemowy)return "System";if(w.Rodzaj=="folder")return "Folder";string e=Path.GetExtension(w.Sciezka).ToLowerInvariant();if(Zawiera(e,".jpg .jpeg .png .webp .bmp .gif .tif .tiff .heic .avif .raw .dng"))return "Zdjęcie";if(Zawiera(e,".mp4 .mkv .avi .mov .wmv .webm .m4v .mts .mpeg"))return "Film";if(Zawiera(e,".flac .mp3 .wav .aac .ogg .m4a .wma .opus"))return "Audio";if(Zawiera(e,".xlsx .xls .csv .ods"))return "Arkusz";if(Zawiera(e,".pdf .doc .docx .txt .rtf .odt .ppt .pptx"))return "Dokument";if(Zawiera(e,".zip .7z .rar .tar .gz .bz2 .xz"))return "Archiwum";if(Zawiera(e,".iso .img .vhd .vhdx .bak .wim .tib"))return "Obraz dysku / backup";if(Zawiera(e,".exe .msi .msix .com"))return "Program";if(Zawiera(e,".cs .js .ts .tsx .py .json .xml .ini .yaml .yml .html .css .dll .ps1 .bat .cmd .sql .config"))return "Kod / konfiguracja";return "Nierozpoznany";}
    static bool Zawiera(string e,string typy){return e!=""&&typy.Split(' ').Contains(e);}
    public static string Symbol(string typ){switch(typ){case "Folder":return "📁";case "System":return "🔒";case "Zdjęcie":return "📷";case "Film":return "🎬";case "Audio":return "♫";case "Arkusz":return "▦";case "Dokument":return "▤";case "Archiwum":return "▣";case "Program":return "⚙";case "Obraz dysku / backup":return "▰";case "Kod / konfiguracja":return "{ }";default:return "?";}}
    public static Color Odcien(string zapis){try{return (Color)ColorConverter.ConvertFromString(zapis);}catch{return Color.FromRgb(137,153,172);}}
    static Brush Material(string kolor,double alfa){Color c=Odcien(kolor);c.A=(byte)Math.Round(Math.Max(0,Math.Min(100,alfa))*2.55);var p=new SolidColorBrush(c);p.Freeze();return p;}
    static string KolorFolderu(Wiersz w){if(w.Systemowy)return "#77818E";var u=Ustawienia;string wynik=u.KolorFolderow;switch(u.TrybFolderow){case "Systemowy / domyślny":wynik="#D6A84B";break;case "Według kategorii":string typ=w.Systemowy?"System":w.Typy[0]>w.Rozmiar*.6?"Film":w.Typy[1]>w.Rozmiar*.6?"Zdjęcie":w.Typy[3]>w.Rozmiar*.6?"Archiwum":"Folder";if(u.KoloryKategorii.ContainsKey(typ))wynik=u.KoloryKategorii[typ];break;case "Według tagów":foreach(var para in u.KoloryTagow)if((w.Oznaczenia??"").Contains(para.Key)){wynik=para.Value;break;}break;case "Według zawartości":wynik=w.Typy[0]>w.Rozmiar*.6?"#4D95BB":w.Typy[1]>w.Rozmiar*.6?"#69A99D":w.Typy[3]>w.Rozmiar*.6?"#A78DC5":"#D6A84B";break;}Color c=Odcien(wynik);if(c.R+c.G+c.B<180)c=Color.FromRgb((byte)Math.Max(80,(int)c.R),(byte)Math.Max(80,(int)c.G),(byte)Math.Max(80,(int)c.B));return c.ToString();}
    static string KolorPlytki(Wiersz w,string typ,ProfilPlytki p){switch(p.TrybKoloru){case "Automatyczny":if(w.Rodzaj=="folder"&&w.Rozmiar>0){if(w.Typy[0]>w.Rozmiar*.6)return "#4D95BB";if(w.Typy[1]>w.Rozmiar*.6)return "#899F98";if(w.Typy[3]>w.Rozmiar*.6)return "#A78DC5";}goto default;case "Jeden własny kolor":return p.Kolor;case "Zależny od koloru folderu":return w.Rodzaj=="folder"?KolorFolderu(w):"#8999AC";case "Neutralny":case "Przezroczysty":return "#8999AC";default:return typ=="Film"?"#4D95BB":typ=="Folder"?"#AA996B":typ=="Archiwum"?"#A78DC5":typ=="Audio"?"#69A99D":"#8999AC";}}
    public static Border Utworz(Wiersz w,bool kompaktowy,Action<Wiersz> klik,Action<Wiersz> otworz,Action<Wiersz> kopie,Func<Wiersz,bool> zaznaczony,double szerokosc=210){
        string typ=Kategoria(w);var p=Ustawienia.Dla(typ);// Karta elementu (ItemCard), pole podglądu (PreviewContainer) i jego szkło (GlassPlate).
        double bok=(szerokosc-20)*Math.Max(.75,Math.Min(.85,.8*p.Rozmiar/112));
        Brush tloNormalne=Material(w.Rodzaj=="folder"?"#302F27":typ=="Film"?"#263344":typ=="Dokument"||typ=="Arkusz"?"#30343D":"#2B3038",91);
        var ramka=new Border {Width=szerokosc,Margin=new Thickness(5),CornerRadius=new CornerRadius(15),Background=tloNormalne,BorderBrush=Program.Kolor("#39434F"),BorderThickness=new Thickness(1),ToolTip=w.Nazwa+Environment.NewLine+w.Sciezka+Environment.NewLine+"Modyfikacja: "+w.DataTekst,Focusable=true};
        ramka.Resources["TloNormalne"]=tloNormalne;var obszar=new Grid();obszar.RowDefinitions.Add(new RowDefinition {Height=new GridLength(1,GridUnitType.Star)});obszar.RowDefinitions.Add(new RowDefinition {Height=GridLength.Auto});ramka.Child=obszar;
        var gora=new StackPanel {Margin=new Thickness(10,6,10,4),ClipToBounds=true};obszar.Children.Add(gora);
        bool material=p.Wlaczona;double promien=p.Ksztalt=="Prawie okrągły"?bok/2:p.Ksztalt=="Bardziej zaokrąglony"?Math.Max(p.Zaokraglenie,25):p.Ksztalt=="Squircle"?Math.Max(p.Zaokraglenie,20):p.Zaokraglenie;
        var plytka=new Border {Width=bok,Height=bok,HorizontalAlignment=HorizontalAlignment.Center,Margin=new Thickness(0,0,0,4),CornerRadius=new CornerRadius(promien),Padding=new Thickness(p.Padding),BorderThickness=new Thickness(material&&p.Obramowanie!="Wyłączone"?p.Grubosc:0),BorderBrush=Material(p.KolorObramowania,p.AlfaObramowania)};
        string kolor=KolorPlytki(w,typ,p);Color mat=Odcien(kolor);double matowosc=Math.Max(0,Math.Min(1,p.Rozmycie/100))*.3;kolor=Color.FromRgb((byte)(mat.R*(1-matowosc)+164*matowosc),(byte)(mat.G*(1-matowosc)+176*matowosc),(byte)(mat.B*(1-matowosc)+190*matowosc)).ToString();double alfa=p.TrybKoloru=="Przezroczysty"?0:100-p.Przezroczystosc;
        double intensywnosc=p.Szklo=="Mocny"?1.8:p.Szklo=="Standardowy"?1.2:p.Szklo=="Minimalny"?.35:p.Szklo=="Wyłączony"?0:.7;
        if(material){plytka.Background=Material(kolor,alfa);if(p.Obramowanie=="Standardowe")plytka.BorderBrush=Material(p.KolorObramowania,Math.Min(100,p.AlfaObramowania*1.5));if(intensywnosc>0&&p.Refleks!="OFF"&&p.TrybKoloru!="Przezroczysty"){Color a=Odcien(kolor);a.A=(byte)Math.Min(255,(alfa+Math.Min(18,(5+p.Rozmycie/10)*intensywnosc))*2.55);Color b=Odcien(kolor);b.A=(byte)(alfa*2.55);plytka.Background=new LinearGradientBrush(a,b,new Point(0,0),new Point(1,1));}}
        var podglad=new Grid();plytka.Child=podglad;gora.Children.Add(plytka);var ikona=Program.Tekst(Symbol(typ),kompaktowy?36:58,w.Rodzaj=="folder"?KolorFolderu(w):"#D8E3F0");ikona.HorizontalAlignment=HorizontalAlignment.Center;ikona.VerticalAlignment=VerticalAlignment.Center;ikona.FontFamily=new FontFamily("Segoe UI Symbol");ikona.FontSize=(bok-2*p.Padding)*p.Ikona/100;podglad.Children.Add(ikona);
        if(w.Rodzaj=="folder"){podglad.Children.Clear();var geometria=Geometry.Parse("M 0,13 L 0,5 Q 0,0 5,0 L 27,0 L 35,10 L 75,10 Q 80,10 80,15 L 80,54 Q 80,60 74,60 L 6,60 Q 0,60 0,54 Z");podglad.Children.Add(new System.Windows.Shapes.Path {Data=geometria,Fill=Program.Kolor(KolorFolderu(w)),Stroke=Program.Kolor(material&&alfa>50&&Odcien(kolor).R+Odcien(kolor).G+Odcien(kolor).B>450?"#283444":"#E3EAF2"),StrokeThickness=1,Stretch=Stretch.Uniform,Width=(bok-2*p.Padding)*p.Ikona/100,VerticalAlignment=VerticalAlignment.Center,HorizontalAlignment=HorizontalAlignment.Center});}
        if(w.Rodzaj=="plik"&&(typ=="Dokument"||typ=="Arkusz")){var format=Program.Tekst(Path.GetExtension(w.Sciezka).TrimStart('.').ToUpperInvariant(),11,"#F3F6FC");format.VerticalAlignment=VerticalAlignment.Bottom;format.HorizontalAlignment=HorizontalAlignment.Center;podglad.Children.Add(format);}
        var nazwa=Program.Tekst(w.Nazwa,13,"#EDF3FC");nazwa.FontWeight=FontWeights.SemiBold;nazwa.TextTrimming=TextTrimming.CharacterEllipsis;nazwa.LineHeight=16;nazwa.LineStackingStrategy=LineStackingStrategy.BlockLineHeight;nazwa.MaxHeight=32;nazwa.ToolTip=w.Nazwa;nazwa.Margin=new Thickness(0,1,0,3);gora.Children.Add(nazwa);
        var info=Program.Tekst(w.Rodzaj=="folder"?"📁 "+w.PlikiTekst+" plików · "+w.RozmiarTekst:Symbol(typ)+" "+Path.GetExtension(w.Sciezka).TrimStart('.').ToUpperInvariant()+" · "+w.RozmiarTekst,11,"#D6E1F0");info.Margin=new Thickness(0,1,0,1);info.TextWrapping=TextWrapping.NoWrap;info.TextTrimming=TextTrimming.CharacterEllipsis;gora.Children.Add(info);
        if(w.Rodzaj=="folder"){var liczba=Program.Tekst(w.PodfolderyTekst+" folderów",11,"#B6C2D4");liczba.Margin=new Thickness(0,1,0,1);gora.Children.Add(liczba);}
        var data=Program.Tekst(w.Rodzaj=="plik"?"Utworzono: "+(w.Utworzenie.HasValue?w.UtworzenieTekst:"ładowanie…"):"Aktywność: "+w.DataTekst,10,"#9DAFC6");data.Margin=new Thickness(0,2,0,3);data.TextWrapping=TextWrapping.NoWrap;data.TextTrimming=TextTrimming.CharacterEllipsis;gora.Children.Add(data);ramka.Tag=w;
        string[] tagi=(w.Oznaczenia??"").Split(new[]{" · "},StringSplitOptions.RemoveEmptyEntries);int limit=kompaktowy?2:3;if(tagi.Length>limit)limit--;
        foreach(string oznaczenie in tagi.Take(limit)){var tag=Program.Tekst("● "+oznaczenie,10,"#BCAE8D");tag.Margin=new Thickness(0,0,0,1);tag.TextWrapping=TextWrapping.NoWrap;tag.TextTrimming=TextTrimming.CharacterEllipsis;tag.ToolTip=oznaczenie;gora.Children.Add(tag);}
        if(tagi.Length>limit){var pozostale=Program.Tekst("+"+(tagi.Length-limit),10,"#9DAFC6");pozostale.Margin=new Thickness(0);pozostale.ToolTip=String.Join(Environment.NewLine,tagi);gora.Children.Add(pozostale);}
        if(w.Kopie>1){var znacznik=Program.Przycisk("⧉ "+w.Kopie,()=>kopie(w));znacznik.ToolTip=w.Kopie+" potwierdzone kopie — kliknij, aby porównać";znacznik.Padding=new Thickness(5,1,5,1);znacznik.FontSize=10;znacznik.HorizontalAlignment=HorizontalAlignment.Right;znacznik.VerticalAlignment=VerticalAlignment.Top;znacznik.Margin=new Thickness(6);obszar.Children.Add(znacznik);}
        else if(w.Kandydaci>1){var znacznik=Program.Tekst("?⧉ "+w.Kandydaci,10,"#CDBA91");znacznik.HorizontalAlignment=HorizontalAlignment.Right;znacznik.ToolTip=w.Kandydaci+" plików o tym samym rozmiarze — potencjalne kopie, niepotwierdzone pełnym hashem";znacznik.VerticalAlignment=VerticalAlignment.Top;znacznik.Margin=new Thickness(6);obszar.Children.Add(znacznik);}
        Action odswiez=()=>{bool wybrany=zaznaczony(w);ramka.BorderBrush=Program.Kolor(wybrany?"#7FB3DF":"#39434F");ramka.BorderThickness=new Thickness(wybrany?2:1);};odswiez();
        ramka.MouseEnter+=(s,e)=>{ramka.RenderTransform=new TranslateTransform(0,-1);if(!zaznaczony(w))ramka.BorderBrush=Program.Kolor("#697C92");if(p.Refleks=="DYNAMICZNY"&&plytka.Background is LinearGradientBrush)((LinearGradientBrush)plytka.Background).StartPoint=new Point(.12,0);};ramka.MouseLeave+=(s,e)=>{ramka.RenderTransform=null;if(plytka.Background is LinearGradientBrush)((LinearGradientBrush)plytka.Background).StartPoint=new Point(0,0);odswiez();};
        ramka.MouseLeftButtonDown+=(s,e)=>{if(e.OriginalSource is Button)return;klik(w);ramka.Focus();odswiez();if(e.ClickCount==2)otworz(w);e.Handled=true;};
        var menu=new ContextMenu();Action<string,Action> dodaj=(etykieta,akcja)=>{var element=new MenuItem {Header=etykieta};element.Click+=(s,e)=>akcja();menu.Items.Add(element);};dodaj("Otwórz",()=>otworz(w));dodaj("Otwórz w Eksploratorze Windows",()=>Program.Eksplorator(w.Rodzaj=="folder"?w.Sciezka:Path.GetDirectoryName(w.Sciezka)));dodaj("Kopiuj ścieżkę",()=>Program.Kopiuj(w.Sciezka));dodaj("Porównaj lokalizacje",()=>kopie(w));ramka.ContextMenu=MenuElementu==null?menu:MenuElementu(w);
        if(w.PrzykladowaMiniatura!=null){podglad.Children.Clear();PokazMiniature(podglad,plytka,w.PrzykladowaMiniatura,typ,null,p,bok);if(!p.RamkaMiniatury){plytka.Background=Brushes.Transparent;plytka.BorderThickness=new Thickness(0);plytka.Padding=new Thickness(0);}}
        if(w.Rodzaj=="plik"&&!w.Przyklad){CancellationTokenSource odwolanie=null;ramka.Unloaded+=(s,e)=>{if(odwolanie!=null)odwolanie.Cancel();};ramka.Loaded+=async(s,e)=>{if(odwolanie!=null)odwolanie.Cancel();odwolanie=new CancellationTokenSource();var biezaceOdwolanie=odwolanie;MetadaneKafelka dane;try{dane=w.MetadanePodgladu??await Metadane(w,biezaceOdwolanie.Token);}catch(OperationCanceledException){return;}if(!ramka.IsLoaded||biezaceOdwolanie.IsCancellationRequested)return;w.MetadanePodgladu=dane;w.Utworzenie=dane.Utworzenie;data.Text="Utworzono: "+w.UtworzenieTekst;if(dane.Szerokosc>0)info.Text=Symbol(typ)+" "+Path.GetExtension(w.Sciezka).TrimStart('.').ToUpperInvariant()+" · "+dane.Szerokosc+"×"+dane.Wysokosc+" · "+w.RozmiarTekst;if(dane.Czas.HasValue)info.Text+=" · "+((long)dane.Czas.Value.TotalHours).ToString("00")+":"+dane.Czas.Value.Minutes.ToString("00")+":"+dane.Czas.Value.Seconds.ToString("00");if(dane.Bity>0)info.Text+=" · "+dane.Bity+"-bit";if(dane.Czestotliwosc>0)info.Text+=" · "+(dane.Czestotliwosc/1000.0).ToString("0.#")+" kHz";if(dane.Strony>0)info.Text+=" · "+dane.Strony+" stron";if(dane.Miniatura!=null){podglad.Children.Clear();PokazMiniature(podglad,plytka,dane.Miniatura,typ,dane.Czas,p,bok);if(!p.RamkaMiniatury){plytka.Background=Brushes.Transparent;plytka.BorderThickness=new Thickness(0);plytka.Padding=new Thickness(0);}}};}
        var cien=new Border {CornerRadius=new CornerRadius(15),Background=Program.Kolor("#30000000"),Margin=new Thickness(1,3,1,0),IsHitTestVisible=false};
        var warstwy=new Grid();warstwy.Children.Add(cien);ramka.Margin=new Thickness(0,0,0,3);warstwy.Children.Add(ramka);
        ramka.MouseEnter+=(s,e)=>{cien.Background=Program.Kolor("#48000000");ramka.Background=Material("#334459",94);};ramka.MouseLeave+=(s,e)=>{cien.Background=Program.Kolor("#30000000");ramka.Background=zaznaczony(w)?Material("#35485F",94):tloNormalne;};

        return new Border {Width=ramka.Width,Margin=new Thickness(5),Child=warstwy,Background=Brushes.Transparent};
    }
    // Miniatura (Thumbnail) wypełnia pole; ikona (Icon) pozostaje przy braku podglądu.
    static void PokazMiniature(Grid podglad,Border plytka,BitmapSource miniatura,string typ,TimeSpan? czas,ProfilPlytki profil,double bok){
        plytka.Padding=new Thickness(profil.RamkaMiniatury?3:0);double wymiar=bok-2*plytka.Padding.Left-2*plytka.BorderThickness.Left;
        podglad.Clip=new RectangleGeometry(new Rect(0,0,wymiar,wymiar),Math.Max(0,plytka.CornerRadius.TopLeft-3),Math.Max(0,plytka.CornerRadius.TopLeft-3));
        podglad.Children.Add(new Image {Source=miniatura,Stretch=Stretch.UniformToFill});
        if(typ=="Film"){var symbol=Program.Tekst("▶",16,"#FFFFFF");symbol.Margin=new Thickness(0);podglad.Children.Add(new Border {Background=Program.Kolor("#88000000"),CornerRadius=new CornerRadius(16),Padding=new Thickness(8,4,8,4),HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Center,Child=symbol});
            if(czas.HasValue){var opis=Program.Tekst(((long)czas.Value.TotalMinutes)+":"+czas.Value.Seconds.ToString("00"),10,"#FFFFFF");opis.Margin=new Thickness(0);podglad.Children.Add(new Border {Background=Program.Kolor("#AA000000"),CornerRadius=new CornerRadius(4),Padding=new Thickness(4,2,4,2),Margin=new Thickness(4),HorizontalAlignment=HorizontalAlignment.Right,VerticalAlignment=VerticalAlignment.Bottom,Child=opis});}}
    }
    public static async Task<MetadaneKafelka> Metadane(Wiersz w,CancellationToken token){token.ThrowIfCancellationRequested();string klucz=w.Sciezka+"|"+w.Rozmiar+"|"+w.Zmiana.ToString("R",System.Globalization.CultureInfo.InvariantCulture);string poprzedni;lock(blokada){if(Ustawienia.KluczeMiniatur.TryGetValue(klucz,out poprzedni))klucz=poprzedni;}lock(blokada){MetadaneKafelka gotowe;if(pamiec.TryGetValue(klucz,out gotowe))return gotowe;}await pracownicy.WaitAsync(token);try{return await Task.Run(()=>{token.ThrowIfCancellationRequested();var dane=new MetadaneKafelka();try{var plik=new FileInfo(w.Sciezka);if(!plik.Exists||(plik.Attributes&(FileAttributes.ReparsePoint|FileAttributes.Offline))!=0||(((int)plik.Attributes)&0x440000)!=0)return dane;dane.Utworzenie=plik.CreationTime;string typ=Kategoria(w);if(typ=="Film"||typ=="Audio"||typ=="Dokument")MetadaneWindows.Uzupelnij(w,dane);if(typ=="Zdjęcie"){
            string katalog=Path.Combine(Program.Katalog,"dane","miniatury");Directory.CreateDirectory(katalog);string nazwa;using(var hash=System.Security.Cryptography.SHA256.Create())nazwa=BitConverter.ToString(hash.ComputeHash(System.Text.Encoding.UTF8.GetBytes(klucz))).Replace("-","")+".png";string sciezka=Path.Combine(katalog,nazwa);
            if(File.Exists(sciezka)){var obraz=new BitmapImage();obraz.BeginInit();obraz.CacheOption=BitmapCacheOption.OnLoad;obraz.UriSource=new Uri(sciezka);obraz.EndInit();obraz.Freeze();dane.Miniatura=obraz;}
            else if(plik.Length<=128*1024*1024){using(var strumien=new FileStream(w.Sciezka,FileMode.Open,FileAccess.Read,FileShare.ReadWrite|FileShare.Delete)){var dekoder=BitmapDecoder.Create(strumien,BitmapCreateOptions.DelayCreation,BitmapCacheOption.None);dane.Szerokosc=dekoder.Frames[0].PixelWidth;dane.Wysokosc=dekoder.Frames[0].PixelHeight;if((long)dane.Szerokosc*dane.Wysokosc>100000000)return dane;strumien.Position=0;var obraz=new BitmapImage();obraz.BeginInit();obraz.CacheOption=BitmapCacheOption.OnLoad;if(dane.Szerokosc>=dane.Wysokosc)obraz.DecodePixelWidth=256;else obraz.DecodePixelHeight=256;obraz.StreamSource=strumien;obraz.EndInit();obraz.Freeze();dane.Miniatura=obraz;if(RezerwujMiniature(katalog)){var zapis=new PngBitmapEncoder();zapis.Frames.Add(BitmapFrame.Create(obraz));using(var cel=new FileStream(sciezka,FileMode.CreateNew,FileAccess.Write,FileShare.Read))zapis.Save(cel);File.WriteAllText(sciezka+".json",Program.Json.Serialize(new[]{dane.Szerokosc,dane.Wysokosc}));}}}
            if(dane.Szerokosc==0&&File.Exists(sciezka+".json")){int[] wymiary=Program.Json.Deserialize<int[]>(File.ReadAllText(sciezka+".json"));dane.Szerokosc=wymiary[0];dane.Wysokosc=wymiary[1];}
        }}catch(IOException){}catch(UnauthorizedAccessException){}catch(NotSupportedException){}catch(System.Runtime.InteropServices.COMException){}catch(System.IO.FileFormatException){}lock(blokada){if(!pamiec.ContainsKey(klucz)){pamiec[klucz]=dane;kolejnosc.Enqueue(klucz);while(kolejnosc.Count>256)pamiec.Remove(kolejnosc.Dequeue());}}return dane;});}finally{pracownicy.Release();}}
}
public sealed class RzadKafelkow:StackPanel {
    public RzadKafelkow(){Orientation=Orientation.Horizontal;DataContextChanged+=(s,e)=>{Children.Clear();var rzad=DataContext as DaneRzedu;if(rzad!=null)foreach(var w in rzad.Elementy)Children.Add(Kafelki.Utworz(w,rzad.Kompaktowy,rzad.Klik,rzad.Otworz,rzad.Kopie,rzad.Zaznaczony,rzad.Szerokosc));};}
}
public sealed class DaneRzedu {public List<Wiersz> Elementy;public bool Kompaktowy;public double Szerokosc;public Action<Wiersz> Klik,Otworz,Kopie;public Func<Wiersz,bool> Zaznaczony;}
}
