using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Threading;

namespace MapaDyskow {
public sealed class StanLokalizacji {
    public string Sciezka,Tryb,Widok,Filtr,Zaznaczenie;public int Strona;public double SkalaDuzych,SkalaKompaktowych,Scroll;
}
public sealed class HistoriaLokalizacji {
    public readonly List<StanLokalizacji> Wpisy=new List<StanLokalizacji>();public int Pozycja=-1;
    public bool Wstecz {get{return Pozycja>0;}}public bool Dalej {get{return Pozycja+1<Wpisy.Count;}}
    public void Dodaj(StanLokalizacji stan){if(Pozycja>=0)Wpisy.RemoveRange(Pozycja+1,Wpisy.Count-Pozycja-1);Wpisy.Add(stan);Pozycja=Wpisy.Count-1;}
    public StanLokalizacji Przejdz(int kierunek){if(kierunek<0?!Wstecz:!Dalej)return null;Pozycja+=kierunek;return Wpisy[Pozycja];}
    public void ZmienSciezki(string stara,string nowa){foreach(var wpis in Wpisy){wpis.Sciezka=OperacjePlikowe.Podmien(wpis.Sciezka,stara,nowa);wpis.Zaznaczenie=OperacjePlikowe.Podmien(wpis.Zaznaczenie,stara,nowa);}}
}
public sealed partial class OknoGlowne {
    HistoriaLokalizacji historia=new HistoriaLokalizacji();StanLokalizacji doPrzywrocenia;bool przywracanie;TextBox edycjaNazwy;bool zatwierdzanie;int wczytanaWersja;string wybierzPoWczytaniu;
    static IEnumerable<DependencyObject> Potomkowie(DependencyObject element){yield return element;for(int i=0;i<VisualTreeHelper.GetChildrenCount(element);i++)foreach(var dziecko in Potomkowie(VisualTreeHelper.GetChild(element,i)))yield return dziecko;}
    ScrollViewer ScrollWidoku(){return Potomkowie(lista.Visibility==Visibility.Visible?(DependencyObject)lista:kafelki).OfType<ScrollViewer>().FirstOrDefault();}
    StanLokalizacji StanWidoku(){var scroll=ScrollWidoku();return new StanLokalizacji {Sciezka=folder,Tryb=tryb,Filtr=szukaj.Text,Strona=strona,Widok=Convert.ToString(wyborWidoku.SelectedItem),SkalaDuzych=Kafelki.Ustawienia.SkalaDuzych,SkalaKompaktowych=Kafelki.Ustawienia.SkalaKompaktowych,Scroll=scroll==null?0:scroll.VerticalOffset,Zaznaczenie=lista.SelectedItem is Wiersz?((Wiersz)lista.SelectedItem).Sciezka:null};}
    void ZapamietajStan(){if(historia.Pozycja>=0)historia.Wpisy[historia.Pozycja]=StanWidoku();}
    void FokusNawigacji(){var obszar=(UIElement)Okno.Content;obszar.Focusable=true;Keyboard.Focus(obszar);lista.CurrentCell=new DataGridCellInfo();}
    void PrzyciskiHistorii(){Kontrolka<Button>("Wstecz").IsEnabled=historia.Wstecz;Kontrolka<Button>("Dalej").IsEnabled=historia.Dalej;Kontrolka<Button>("Nadrzedny").IsEnabled=folder!=""&&!String.IsNullOrEmpty(Path.GetDirectoryName(folder.TrimEnd('\\')));Kontrolka<Button>("NowyFolder").IsEnabled=folder!=""&&!zajety;}
    void PokazBreadcrumb(){var panel=Kontrolka<WrapPanel>("Breadcrumb");panel.Children.Clear();if(folder=="")return;string korzen=Path.GetPathRoot(folder),aktualna=korzen;Action<string,string> dodaj=(nazwa,sciezka)=>{if(panel.Children.Count>0)panel.Children.Add(Program.Tekst(" › ",12,"#94A5C0"));var przycisk=Program.Przycisk(nazwa,()=>OtworzFolder(sciezka));przycisk.Padding=new Thickness(5,2,5,2);przycisk.ToolTip=sciezka;panel.Children.Add(przycisk);};dodaj("Dysk "+korzen.TrimEnd('\\'),korzen);foreach(string segment in folder.Substring(korzen.Length).Split(new[]{'\\'},StringSplitOptions.RemoveEmptyEntries)){aktualna=Path.Combine(aktualna,segment);dodaj(segment,aktualna);}}
    void Nawiguj(string sciezka){if(edycjaNazwy!=null&&!ZatwierdzNazwe())return;if(tryb=="Folder"&&folder.Equals(sciezka,StringComparison.OrdinalIgnoreCase))return;ZapamietajStan();FokusNawigacji();folder=sciezka;tryb="Folder";strona=0;przywracanie=true;sekcje.SelectedIndex=-1;szukaj.Text="";opoznienie.Stop();przywracanie=false;historia.Dodaj(StanWidoku());doPrzywrocenia=new StanLokalizacji {Scroll=0};PrzyciskiHistorii();OdswiezListe();}
    void Historia(int kierunek){if(edycjaNazwy!=null&&!ZatwierdzNazwe())return;ZapamietajStan();var wpis=historia.Przejdz(kierunek);if(wpis==null)return;FokusNawigacji();przywracanie=true;folder=wpis.Sciezka;tryb=wpis.Tryb;strona=wpis.Strona;sekcje.SelectedItem=tryb=="Folder"?null:tryb;szukaj.Text=wpis.Filtr??"";opoznienie.Stop();Kafelki.Ustawienia.Widoki[KluczWidoku()]=wpis.Widok;Kafelki.Ustawienia.SkalaDuzych=wpis.SkalaDuzych;Kafelki.Ustawienia.SkalaKompaktowych=wpis.SkalaKompaktowych;przywracanie=false;doPrzywrocenia=wpis;PrzyciskiHistorii();OdswiezListe();}
    void Nadrzedny(){if(folder=="")return;string rodzic=Path.GetDirectoryName(folder.TrimEnd('\\'));if(String.IsNullOrEmpty(rodzic))return;if(rodzic.EndsWith(":"))rodzic+="\\";OtworzFolder(rodzic);}
    void PrzywrocStan(){var wpis=doPrzywrocenia;doPrzywrocenia=null;string wybor=wybierzPoWczytaniu??(wpis==null?null:wpis.Zaznaczenie);wybierzPoWczytaniu=null;int wersjaWidoku=wersja;Dispatcher.CurrentDispatcher.BeginInvoke(DispatcherPriority.ContextIdle,new Action(()=>{if(wersjaWidoku!=wersja)return;if(wybor!=null){var element=ostatnie.FirstOrDefault(w=>w.Sciezka.Equals(wybor,StringComparison.OrdinalIgnoreCase));if(element!=null){lista.SelectedItem=element;zaznaczone.Add(element);OdswiezZaznaczenie(kafelki);}}if(wpis!=null){Okno.UpdateLayout();var scroll=ScrollWidoku();if(scroll!=null)scroll.ScrollToVerticalOffset(wpis.Scroll);}}));}
    public static string SkrotKlawisza(Key klawisz,ModifierKeys modyfikatory,bool tekst){if(modyfikatory==ModifierKeys.Alt){if(klawisz==Key.Left)return "wstecz";if(klawisz==Key.Right)return "dalej";if(klawisz==Key.Up)return "rodzic";}if(modyfikatory==(ModifierKeys.Control|ModifierKeys.Shift)&&klawisz==Key.N)return "nowy";if(klawisz==Key.F5&&modyfikatory==ModifierKeys.None)return "odswiez";if(tekst)return "";if(modyfikatory!=ModifierKeys.None)return "";return klawisz==Key.Back?"wstecz":klawisz==Key.F2?"nazwa":klawisz==Key.F5?"odswiez":klawisz==Key.Enter?"otworz":"";}
    public static string SkrotMyszy(MouseButton przycisk){return przycisk==MouseButton.XButton1?"wstecz":przycisk==MouseButton.XButton2?"dalej":"";}
    void WykonajSkrot(string akcja){if(akcja=="wstecz")Historia(-1);else if(akcja=="dalej")Historia(1);else if(akcja=="rodzic")Nadrzedny();else if(akcja=="nowy")UtworzFolder();else if(akcja=="nazwa")EdytujNazwe(lista.SelectedItem as Wiersz);else if(akcja=="odswiez")OdswiezBiezacy();else if(akcja=="otworz"&&lista.SelectedItem is Wiersz)OtworzElement((Wiersz)lista.SelectedItem);}
    void PrzygotujNawigacje(){
        Kontrolka<Button>("Wstecz").Click+=(s,e)=>Historia(-1);Kontrolka<Button>("Dalej").Click+=(s,e)=>Historia(1);Kontrolka<Button>("Nadrzedny").Click+=(s,e)=>Nadrzedny();Kontrolka<Button>("NowyFolder").Click+=(s,e)=>UtworzFolder();
        Okno.PreviewKeyDown+=(s,e)=>{var klawisz=e.Key==Key.System?e.SystemKey:e.Key;bool tekst=Keyboard.FocusedElement is TextBoxBase||Keyboard.FocusedElement is PasswordBox||(Keyboard.FocusedElement is ComboBox&&((ComboBox)Keyboard.FocusedElement).IsEditable);string akcja=SkrotKlawisza(klawisz,Keyboard.Modifiers,tekst);if(akcja!=""){e.Handled=true;WykonajSkrot(akcja);}};
        Okno.PreviewMouseDown+=(s,e)=>{string akcja=SkrotMyszy(e.ChangedButton);if(akcja!=""){e.Handled=true;WykonajSkrot(akcja);}};
        Kafelki.MenuElementu=MenuElementu;lista.ContextMenu=new ContextMenu();lista.ContextMenuOpening+=(s,e)=>{var element=e.OriginalSource as DependencyObject;var w=ZnajdzWiersz(element);if(w!=null)lista.SelectedItem=w;lista.ContextMenu=MenuElementu(w);};kafelki.ContextMenu=MenuElementu(null);
        PrzyciskiHistorii();
    }
    Wiersz ZnajdzWiersz(DependencyObject element){while(element!=null){var kontrolka=element as FrameworkElement;if(kontrolka!=null){if(kontrolka.Tag is Wiersz)return (Wiersz)kontrolka.Tag;if(kontrolka.DataContext is Wiersz)return (Wiersz)kontrolka.DataContext;}element=VisualTreeHelper.GetParent(element);}return null;}
    ContextMenu MenuElementu(Wiersz w){var menu=new ContextMenu();Action<string,Action> dodaj=(nazwa,akcja)=>{var pozycja=new MenuItem {Header=nazwa};pozycja.Click+=(s,e)=>akcja();menu.Items.Add(pozycja);};if(w==null){dodaj("Nowy folder",()=>UtworzFolder());menu.Items.Add(new Separator());dodaj("Odśwież",()=>OdswiezBiezacy());return menu;}dodaj("Otwórz",()=>OtworzElement(w));dodaj(w.Rodzaj=="folder"?"Otwórz w Eksploratorze Windows":"Pokaż lokalizację",()=>{if(w.Rodzaj=="folder")Program.Eksplorator(w.Sciezka);else OtworzFolder(Path.GetDirectoryName(w.Sciezka));});if(w.Rodzaj=="plik")dodaj("Porównaj kopie",()=>PokazKopie(w));menu.Items.Add(new Separator());if(w.Rodzaj=="folder"&&!w.Przyklad)dodaj("Nowy folder",()=>UtworzFolder());if(!w.Przyklad&&(w.Rodzaj=="plik"||w.Rodzaj=="folder"))dodaj("Zmień nazwę",()=>EdytujNazwe(w));menu.Items.Add(new Separator());dodaj("Kopiuj ścieżkę",()=>Program.Kopiuj(w.Sciezka));dodaj("Właściwości",()=>PokazSzczegoly(w));return menu;}
    void UtworzFolder(){if(folder==""||zajety)return;if(edycjaNazwy!=null&&!ZatwierdzNazwe())return;try{string nowa=OperacjePlikowe.NowyFolder(folder);szukaj.Text="";opoznienie.Stop();using(var baza=new Baza(Program.Indeks,false)){var elementy=ZawartoscFolderu(baza,folder,"",systemowe.IsChecked==true,int.MaxValue-1,0);strona=Math.Max(0,elementy.FindIndex(w=>w.Sciezka.Equals(nowa,StringComparison.OrdinalIgnoreCase)))/Program.Ustawienia.rozmiarStrony;}OdswiezListe();PoczekajNaEdycje(nowa);}catch(Exception blad){MessageBox.Show(Okno,"Nie udało się utworzyć folderu.\n"+OperacjePlikowe.Komunikat(blad),"Nowy folder");}}
    async void PoczekajNaEdycje(string sciezka){int aktualna=wersja;for(int proba=0;proba<100&&aktualna==wersja;proba++){await System.Threading.Tasks.Task.Delay(30);var w=ostatnie.FirstOrDefault(p=>p.Sciezka==sciezka);if(w!=null&&wczytanaWersja==aktualna){await Dispatcher.Yield(DispatcherPriority.Background);Okno.UpdateLayout();EdytujNazwe(w);return;}}stan.Text="Folder utworzono. Jeśli nie jest widoczny na tej stronie, znajdź go i użyj F2.";}
    void EdytujNazwe(Wiersz w){if(w==null||zajety||(w.Rodzaj!="folder"&&w.Rodzaj!="plik"))return;if(edycjaNazwy!=null&&!ZatwierdzNazwe())return;lista.SelectedItem=w;
        var korzen=lista.Visibility==Visibility.Visible?(DependencyObject)lista:kafelki;var nazwa=Potomkowie(korzen).OfType<TextBlock>().FirstOrDefault(t=>t.Text==w.Nazwa&&ZnajdzWiersz(t)==w);if(nazwa==null){stan.Text="Przewiń do elementu, aby edytować jego nazwę.";return;}var panel=nazwa.Parent as Panel;if(panel==null)return;var wierszListy=lista.ItemContainerGenerator.ContainerFromItem(w) as DataGridRow;double wysokoscWiersza=wierszListy==null?0:wierszListy.Height;if(wierszListy!=null)wierszListy.Height=78;int miejsce=panel.Children.IndexOf(nazwa);var uklad=new StackPanel();var pole=new TextBox {Text=w.Nazwa,Tag=w,MinWidth=100,Padding=new Thickness(3)};var komunikat=Program.Tekst("",10,"#FFBCA0");komunikat.Margin=new Thickness(0);uklad.Children.Add(pole);uklad.Children.Add(komunikat);panel.Children.RemoveAt(miejsce);panel.Children.Insert(miejsce,uklad);edycjaNazwy=pole;
        Action anuluj=()=>{if(wierszListy!=null)wierszListy.Height=wysokoscWiersza;edycjaNazwy=null;panel.Children.Remove(uklad);panel.Children.Insert(miejsce,nazwa);};pole.Resources["Anuluj"]=anuluj;pole.Resources["Blad"]=komunikat;
        pole.PreviewKeyDown+=(s,e)=>{if(e.Key==Key.Escape){e.Handled=true;anuluj();}else if(e.Key==Key.Enter){e.Handled=true;ZatwierdzNazwe();}};pole.LostKeyboardFocus+=(s,e)=>{if(edycjaNazwy==pole&&!zatwierdzanie)ZatwierdzNazwe();};pole.Focus();pole.Select(0,OperacjePlikowe.DlugoscZaznaczenia(w.Nazwa,w.Rodzaj=="plik"));
    }
    bool ZatwierdzNazwe(){if(edycjaNazwy==null)return true;if(zatwierdzanie)return false;var pole=edycjaNazwy;var w=(Wiersz)pole.Tag;string blad=OperacjePlikowe.Waliduj(pole.Text);if(blad!=""){((TextBlock)pole.Resources["Blad"]).Text=blad;Dispatcher.CurrentDispatcher.BeginInvoke(new Action(()=>pole.Focus()));return false;}zatwierdzanie=true;try{
        if(w.Rodzaj=="plik"&&OperacjePlikowe.ZmieniaRozszerzenie(w.Nazwa,pole.Text)&&!PotwierdzRozszerzenie()){pole.Focus();return false;}
        string stara=w.Sciezka,nowa=OperacjePlikowe.ZmienNazwe(stara,pole.Text,w.Rodzaj=="folder");edycjaNazwy=null;historia.ZmienSciezki(stara,nowa);folder=OperacjePlikowe.Podmien(folder,stara,nowa);foreach(var para in Kafelki.Ustawienia.Widoki.ToList()){string klucz=OperacjePlikowe.Podmien(para.Key,stara,nowa);if(klucz!=para.Key){Kafelki.Ustawienia.Widoki.Remove(para.Key);Kafelki.Ustawienia.Widoki[klucz]=para.Value;}}foreach(var para in Kafelki.Ustawienia.UkladyFolderow.ToList()){string klucz=OperacjePlikowe.Podmien(para.Key,stara,nowa);if(klucz!=para.Key){Kafelki.Ustawienia.UkladyFolderow.Remove(para.Key);Kafelki.Ustawienia.UkladyFolderow[klucz]=para.Value;}}try{Kafelki.Zapisz();}catch(IOException){}catch(UnauthorizedAccessException){}ZapamietajStan();wybierzPoWczytaniu=nowa;ZaladujDyski();OdswiezListe();return true;
    }catch(Exception wyjatek){((TextBlock)pole.Resources["Blad"]).Text=OperacjePlikowe.Komunikat(wyjatek);pole.Focus();return false;}finally{zatwierdzanie=false;}}
    bool PotwierdzRozszerzenie(){var okno=new Window {Owner=Okno,Title="Zmiana rozszerzenia",Width=470,Height=210,ResizeMode=ResizeMode.NoResize,WindowStartupLocation=WindowStartupLocation.CenterOwner,Background=Program.Kolor("#181E28")};var panel=new StackPanel {Margin=new Thickness(20)};okno.Content=panel;panel.Children.Add(Program.Tekst("Zmiana rozszerzenia nazwy pliku może spowodować, że plik stanie się bezużyteczny.\nCzy na pewno chcesz je zmienić?",14,"#FFFFFF"));var przyciski=new StackPanel {Orientation=Orientation.Horizontal};panel.Children.Add(przyciski);przyciski.Children.Add(Program.Przycisk("Zmień",()=>okno.DialogResult=true));var anuluj=Program.Przycisk("Anuluj",()=>okno.DialogResult=false);anuluj.IsCancel=true;przyciski.Children.Add(anuluj);return okno.ShowDialog()==true;}
    void OdswiezBiezacy(){if(edycjaNazwy!=null&&!ZatwierdzNazwe())return;OdswiezListe();}
}
}