using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Interop;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;

namespace MapaDyskow {
public sealed class Konfiguracja {
    public string plikBazy {get;set;} public int rozmiarStrony {get;set;}
    public double duzyFolderGiB {get;set;} public double bardzoDuzyFolderGiB {get;set;}
    public int stareDaneDni {get;set;} public bool domyslniePokazSystemowe {get;set;} public bool pelneHashePrzyOdswiezaniu {get;set;}
}
public sealed class Wiersz {
    public long Piksele {get{return MetadanePodgladu==null?0:(long)MetadanePodgladu.Szerokosc*MetadanePodgladu.Wysokosc;}}
    public double Sekundy {get{return MetadanePodgladu==null||!MetadanePodgladu.Czas.HasValue?0:MetadanePodgladu.Czas.Value.TotalSeconds;}}
    public string WymiaryTekst {get{return Piksele==0?"—":MetadanePodgladu.Szerokosc+" × "+MetadanePodgladu.Wysokosc;}}
    public string CzasTekst {get{return Sekundy==0?"—":TimeSpan.FromSeconds(Sekundy).ToString();}}
    public string SymbolSzczegolow {get{return Rodzaj=="folder"?"\uE8B7":TypTekst=="Film"?"\uE714":TypTekst=="Zdjęcie"?"\uE91B":TypTekst=="Audio"?"\uE8D6":"\uE8A5";}}
    public string TagiKrotkie {get{var tagi=(Oznaczenia??"").Split(new[]{" · "},StringSplitOptions.RemoveEmptyEntries);return String.Join(" · ",tagi.Take(2).Select(t=>System.Globalization.CultureInfo.GetCultureInfo("pl-PL").TextInfo.ToTitleCase(t.ToLowerInvariant())))+(tagi.Length>2?" · +"+(tagi.Length-2):"");}}
    public DateTime? Utworzenie {get;set;} public long Kopie {get;set;} public long Kandydaci {get;set;} public bool Przyklad {get;set;}
    public bool WIndeksie; public string BladOdczytu; public DateTime? Dostep; public FileAttributes? Atrybuty; public MetadaneKafelka MetadanePodgladu;
    public BitmapSource PrzykladowaMiniatura {get;set;}
    public string UtworzenieTekst {get{return Utworzenie.HasValue?Utworzenie.Value.ToString("yyyy-MM-dd"):"Brak danych";}}
    public string Rozszerzenie {get{return Rodzaj=="plik"?Path.GetExtension(Sciezka).TrimStart('.').ToUpperInvariant():"";}}
    public string TypTekst {get{return Kafelki.Kategoria(this);}}
    public string StatusDuplikatu {get{return Kopie>1?"⧉ "+Kopie+" · SHA-256":Kandydaci>1?"?⧉ "+Kandydaci+" · rozmiar":Rodzaj=="folder"&&Duplikaty>0?"Grupy w poddrzewie":"—";}}
    public string Nazwa {get;set;} public string Sciezka {get;set;} public string Rodzaj {get;set;} public string Hash {get;set;}
    public long Rozmiar {get;set;} public long Pliki {get;set;} public long Podfoldery {get;set;} public double Zmiana {get;set;}
    public long[] Typy=new long[5]; public long Duplikaty; public bool Sygnal; public bool Systemowy; public string Uwagi=""; public long Grupa; public long Potencjal; public long Zajete; public long Niepewne;
    public string Oznaczenia {get;set;}
    public string RozmiarTekst {get{return Program.Rozmiar(Rozmiar);}}
    public string PlikiTekst {get{return Pliki<0?"—":Pliki.ToString("N0");}}
    public string PodfolderyTekst {get{return Podfoldery<0?"—":Podfoldery.ToString("N0");}}
    public string DataTekst {get{return Program.Data(Zmiana);}}
    public string PotencjalTekst {get{return Program.Rozmiar(Potencjal);}}
    public string ZajeteTekst {get{return Program.Rozmiar(Zajete);}}
}
public static class Program {
    public static ResourceDictionary Zasoby; public static string Katalog=AppDomain.CurrentDomain.BaseDirectory; public static string Indeks; public static string KatalogAudytu; public static Konfiguracja Ustawienia;
    public static JavaScriptSerializer Json=new JavaScriptSerializer {MaxJsonLength=int.MaxValue};
    public static readonly string KolumnyFolderu="sciezka,nazwa,rozmiar,pliki,podfoldery,zmiana,filmy,zdjecia,dokumenty,archiwa,inne,duplikaty,sygnal,systemowy,uwagi";
    public static readonly DateTime Epoka=new DateTime(1970,1,1,0,0,0,DateTimeKind.Utc);
    public static string Rozmiar(long liczba){if(liczba<0)return "Nie przeskanowano";string[] jednostki={"B","KiB","MiB","GiB","TiB"};double wartosc=liczba;int i=0;while(wartosc>=1024&&i<4){wartosc/=1024;i++;}return wartosc.ToString(i==0?"N0":"N2")+" "+jednostki[i];}
    public static string Data(double czas){return czas<=0?"Brak danych":Epoka.AddSeconds(czas).ToLocalTime().ToString("yyyy-MM-dd HH:mm");}
    public static string Prefiks(string sciezka){return sciezka.TrimEnd('\\').Replace("^","^^").Replace("%","^%").Replace("_","^_")+"\\%";}
    public static Brush Kolor(string kolor){return (Brush)new BrushConverter().ConvertFromString(kolor);}
    public static TextBlock Tekst(string tekst,int wielkosc,string kolor){return new TextBlock {Text=tekst,FontSize=wielkosc,Foreground=Kolor(kolor),TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,4,0,4)};}
    public static Button Przycisk(string tekst,Action akcja){var przycisk=new Button {Content=tekst,Margin=new Thickness(3),Padding=new Thickness(10,7,10,7),Background=Kolor("#26354A"),Foreground=Brushes.White,BorderBrush=Kolor("#41536D")};przycisk.Click+=(s,e)=>akcja();return przycisk;}
    public static Wiersz Folder(object[] r){var w=new Wiersz {Sciezka=(string)r[0],Nazwa=(string)r[1],Rozmiar=Convert.ToInt64(r[2]),Pliki=Convert.ToInt64(r[3]),Podfoldery=Convert.ToInt64(r[4]),Zmiana=Convert.ToDouble(r[5]),Duplikaty=Convert.ToInt64(r[11]),Sygnal=Convert.ToInt64(r[12])!=0,Systemowy=Convert.ToInt64(r[13])!=0,Uwagi=Convert.ToString(r[14]),Rodzaj="folder",WIndeksie=true};for(int i=0;i<5;i++)w.Typy[i]=Convert.ToInt64(r[i+6]);w.Oznaczenia=Tagi(w);return w;}
    public static Wiersz Plik(object[] r){return new Wiersz {Sciezka=(string)r[0],Nazwa=Path.GetFileName((string)r[0]),Rozmiar=Convert.ToInt64(r[1]),Zmiana=Convert.ToDouble(r[2]),Rodzaj="plik",WIndeksie=true,Hash=Convert.ToString(r[4]),Oznaczenia=Convert.ToString(r[3])};}
    public static Wiersz Grupa(object[] r){return new Wiersz {Grupa=Convert.ToInt64(r[0]),Hash=(string)r[1],Nazwa="Identyczna zawartość · "+((string)r[1]).Substring(0,12),Sciezka="SHA-256: "+r[1],Rozmiar=Convert.ToInt64(r[2]),Pliki=Convert.ToInt64(r[3]),Zajete=Convert.ToInt64(r[5]),Potencjal=Convert.ToInt64(r[6]),Niepewne=Convert.ToInt64(r[7]),Rodzaj="duplikat",Oznaczenia=Convert.ToInt64(r[7])>0?"TOŻSAMOŚĆ DO WERYFIKACJI":"POTWIERDZONY SHA-256"};}
    public static string Tagi(Wiersz w){var tagi=new List<string>();if(w.Systemowy)tagi.Add("SYSTEMOWY — NIE RUSZAĆ");if(w.Rozmiar<0)tagi.Add("NIEPRZESKANOWANY");if(w.Rozmiar>=Ustawienia.bardzoDuzyFolderGiB*1073741824L)tagi.Add("BARDZO DUŻY");else if(w.Rozmiar>=Ustawienia.duzyFolderGiB*1073741824L)tagi.Add("DUŻY FOLDER");if(Regex.IsMatch(w.Nazwa,@"telefon|fona|redmi|samsung|dcim|camera|zgryw",RegexOptions.IgnoreCase))tagi.Add("ZGRYW TELEFONU");if(w.Sygnal)tagi.Add("BACKUP / ARCHIWUM");if(w.Rozmiar>0&&w.Typy[0]>w.Rozmiar*0.6)tagi.Add("DUŻO FILMÓW");if(w.Rozmiar>0&&w.Typy[1]>w.Rozmiar*0.6)tagi.Add("DUŻO ZDJĘĆ");if(w.Duplikaty>0)tagi.Add("POTENCJALNE DUPLIKATY");if(w.Zmiana>0&&Epoka.AddSeconds(w.Zmiana)<DateTime.UtcNow.AddDays(-Ustawienia.stareDaneDni))tagi.Add("STARE DANE");if(!String.IsNullOrEmpty(w.Uwagi))tagi.Add("WYMAGA UWAGI");if(w.Sygnal||w.Duplikaty>0)tagi.Add("DO PRZEJRZENIA");return String.Join(" · ",tagi);}
    public static void Eksplorator(string sciezka){try{if(!Regex.IsMatch(sciezka,@"^[a-zA-Z]:\\"))throw new InvalidOperationException("Wymagana jest pełna ścieżka lokalna.");string folder=sciezka;if(!Directory.Exists(folder))throw new IOException("Folder nie jest obecnie dostępny. Indeks jest zapisem audytu.");if(folder.EndsWith("\\"))folder+=".";Process.Start(new ProcessStartInfo(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Windows),"explorer.exe"),"\""+folder+"\""){UseShellExecute=true});}catch(Exception blad){MessageBox.Show(blad.Message,"Otwieranie folderu");}}
    public static void Kopiuj(string sciezka){try{Clipboard.SetText(sciezka);}catch(Exception blad){MessageBox.Show(blad.Message,"Schowek");}}
    [STAThread] public static int Main(string[] argumenty){AppDomain.CurrentDomain.UnhandledException+=(s,e)=>File.WriteAllText(Path.Combine(Katalog,"blad-krytyczny.log"),Convert.ToString(e.ExceptionObject),Encoding.UTF8);try{
        Ustawienia=Json.Deserialize<Konfiguracja>(File.ReadAllText(Path.Combine(Katalog,"konfiguracja.json"),Encoding.UTF8));Ustawienia.rozmiarStrony=Math.Max(25,Math.Min(500,Ustawienia.rozmiarStrony));
        if(String.IsNullOrWhiteSpace(Ustawienia.plikBazy)||Path.IsPathRooted(Ustawienia.plikBazy))throw new InvalidOperationException("Ścieżka bazy musi być względna względem katalogu aplikacji.");
        Indeks=Path.GetFullPath(Path.Combine(Katalog,Ustawienia.plikBazy));if(!Indeks.StartsWith(Path.GetFullPath(Katalog).TrimEnd('\\')+"\\",StringComparison.OrdinalIgnoreCase))throw new InvalidOperationException("Baza aplikacji musi być osobną kopią w jej katalogu. Oryginalne bazy poza aplikacją są chronione.");
        KatalogAudytu="";string plikPochodzenia=Path.Combine(Katalog,"dane","pochodzenie.json");
        if(File.Exists(plikPochodzenia)){var pochodzenie=Json.Deserialize<Dictionary<string,object>>(File.ReadAllText(plikPochodzenia,Encoding.UTF8));KatalogAudytu=Path.GetFullPath(Path.Combine(Katalog,Convert.ToString(pochodzenie["katalog_wynikow_audytu"])));if(Indeks.Equals(Path.GetFullPath(Path.Combine(Katalog,Convert.ToString(pochodzenie["oryginalny_indeks"]))),StringComparison.OrdinalIgnoreCase))throw new InvalidOperationException("Oryginalny indeks audytu jest chroniony. Użyj osobnej kopii aplikacji.");}
        if(!File.Exists(Indeks))Baza.UtworzPustyIndeks(Indeks);
        if(argumenty.Length>0&&argumenty[0]=="--test"){SprawdzIndeks();return 0;}
        if(argumenty.Length>0&&argumenty[0]=="--testy"){Testy.Uruchom();return 0;}
        if(argumenty.Length>1&&(argumenty[0]=="--test-skan"||argumenty[0]=="--test-anuluj")){var token=new CancellationTokenSource();bool anuluj=argumenty[0]=="--test-anuluj";try{var wynik=Skaner.Skanuj(argumenty[1],true,token.Token,s=>{if(anuluj)token.Cancel();});File.WriteAllText(Path.Combine(Katalog,"test-skan.json"),Json.Serialize(wynik),Encoding.UTF8);}catch(OperationCanceledException){if(!anuluj)throw;File.WriteAllText(Path.Combine(Katalog,"test-anuluj.json"),"{\"anulowano\":true}",Encoding.UTF8);}return 0;}
        var aplikacja=new Application();aplikacja.ShutdownMode=ShutdownMode.OnMainWindowClose;SynchronizationContext.SetSynchronizationContext(new DispatcherSynchronizationContext(Dispatcher.CurrentDispatcher));
        var okno=new OknoGlowne();aplikacja.MainWindow=okno.Okno;
        aplikacja.DispatcherUnhandledException+=(s,e)=>{File.AppendAllText(Path.Combine(Katalog,"bledy.log"),DateTime.UtcNow.ToString("o")+" "+e.Exception+Environment.NewLine);if(argumenty.Length==0)MessageBox.Show(e.Exception.Message,"Mapa dysków — błąd");e.Handled=true;};
        if(argumenty.Length>1&&argumenty[0]=="--zrzuty"){aplikacja.DispatcherUnhandledException+=(s,e)=>{throw new InvalidOperationException("Test UI",e.Exception);};okno.ZapiszZrzuty(argumenty[1]);return 0;}
        aplikacja.Run(okno.Okno);return 0;
    }catch(Exception blad){File.WriteAllText(Path.Combine(Katalog,"blad-uruchomienia.log"),blad.ToString(),Encoding.UTF8);if(argumenty.Length==0)MessageBox.Show(blad.Message,"Nie można uruchomić Mapy dysków");return 1;}}
    static void SprawdzIndeks(){using(var baza=new Baza(Indeks,false)){var wynik=new Dictionary<string,object>();wynik["pliki"]=baza.Wartosc("SELECT count(*) FROM pliki");wynik["foldery"]=baza.Wartosc("SELECT count(*) FROM widok_folderow");wynik["duplikaty"]=baza.Wartosc("SELECT count(*) FROM grupy_duplikatow");wynik["potencjal"]=baza.Wartosc("SELECT sum(potencjal) FROM grupy_duplikatow");var zegar=Stopwatch.StartNew();var wiersze=baza.Zapytaj("SELECT "+KolumnyFolderu+" FROM widok_folderow WHERE systemowy=0 ORDER BY rozmiar DESC LIMIT 200");wynik["czas_strony_ms"]=zegar.ElapsedMilliseconds;wynik["wiersze_strony"]=wiersze.Count;wynik["pierwszy_folder"]=wiersze.Count==0?null:Folder(wiersze[0]).Sciezka;wynik["integralnosc"]=baza.Wartosc("PRAGMA quick_check");if(Convert.ToString(wynik["integralnosc"])!="ok")throw new Exception("Niepoprawny indeks.");File.WriteAllText(Path.Combine(Katalog,"test-indeks.json"),Json.Serialize(wynik),Encoding.UTF8);}}
}
public sealed partial class OknoGlowne {
    public Window Okno;DataGrid lista;TreeView drzewo;ListBox sekcje;StackPanel szczegoly;TextBox szukaj,sciezkaWidoku;TextBlock naglowek,stan,numer,opis;CheckBox systemowe;Button poprzednia,nastepna;DispatcherTimer opoznienie;int strona,wersja;string tryb="Największe foldery",folder="";bool zajety,gotowe;HashSet<int> stronyLokalizacji=new HashSet<int>();CancellationTokenSource anulowanie;List<Wiersz> ostatnie=new List<Wiersz>();
    string[] nazwySekcji={"Największe foldery","Największe pliki","Zgrywy telefonów","Filmy","Zdjęcia","Archiwa i backupy","Potwierdzone duplikaty","Foldery wymagające uwagi","Potencjalnie odzyskiwane miejsce"};
    [DllImport("dwmapi.dll")] static extern int DwmSetWindowAttribute(IntPtr okno,int atrybut,ref int wartosc,int rozmiar);
    public OknoGlowne(){using(var strumien=Assembly.GetExecutingAssembly().GetManifestResourceStream("Interfejs.xaml"))Okno=(Window)XamlReader.Load(strumien);Program.Zasoby=Okno.Resources;lista=Kontrolka<DataGrid>("Lista");drzewo=Kontrolka<TreeView>("Drzewo");sekcje=Kontrolka<ListBox>("Sekcje");szczegoly=Kontrolka<StackPanel>("Szczegoly");szukaj=Kontrolka<TextBox>("Szukaj");sciezkaWidoku=Kontrolka<TextBox>("SciezkaWidoku");naglowek=Kontrolka<TextBlock>("Naglowek");stan=Kontrolka<TextBlock>("Stan");numer=Kontrolka<TextBlock>("NumerStrony");opis=Kontrolka<TextBlock>("OpisWidoku");systemowe=Kontrolka<CheckBox>("PokazSystemowe");poprzednia=Kontrolka<Button>("Poprzednia");nastepna=Kontrolka<Button>("Nastepna");
        sekcje.ItemsSource=nazwySekcji;systemowe.IsChecked=Program.Ustawienia.domyslniePokazSystemowe;sekcje.SelectionChanged+=(s,e)=>{if(!gotowe||przywracanie||sekcje.SelectedItem==null)return;if(edycjaNazwy!=null&&!ZatwierdzNazwe())return;ZapamietajStan();tryb=Convert.ToString(sekcje.SelectedItem);folder="";strona=0;historia.Dodaj(StanWidoku());PrzyciskiHistorii();OdswiezListe();};
        opoznienie=new DispatcherTimer {Interval=TimeSpan.FromMilliseconds(350)};opoznienie.Tick+=(s,e)=>{opoznienie.Stop();strona=0;OdswiezListe();};szukaj.TextChanged+=(s,e)=>{if(gotowe){opoznienie.Stop();opoznienie.Start();}};
        systemowe.Click+=(s,e)=>{strona=0;OdswiezListe();};poprzednia.Click+=(s,e)=>{if(strona>0){strona--;OdswiezListe();}};nastepna.Click+=(s,e)=>{strona++;OdswiezListe();};
        lista.SelectionChanged+=(s,e)=>{var wybrany=lista.SelectedItem as Wiersz;PokazInformacjeZaznaczenia();};lista.MouseDoubleClick+=(s,e)=>{var w=lista.SelectedItem as Wiersz;if(w==null)return;if(w.Rodzaj=="folder")OtworzFolder(w.Sciezka);else if(w.Rodzaj=="duplikat")Porownaj(w);else OtworzElement(w);};

        Kontrolka<Button>("PorownajWybrane").Click+=(s,e)=>PorownajWybrany();Kontrolka<Button>("Odswiez").Click+=(s,e)=>OknoSkanowania();
        Okno.SourceInitialized+=(s,e)=>{int wartosc=1;try{DwmSetWindowAttribute(new WindowInteropHelper(Okno).Handle,20,ref wartosc,4);}catch{}};
        Okno.Closing+=(s,e)=>{if(zajety){if(MessageBox.Show("Przerwać skan i zamknąć aplikację? Nieukończony zakres zostanie wycofany w indeksie.","Trwa skan",MessageBoxButton.YesNo)!=MessageBoxResult.Yes){e.Cancel=true;return;}if(anulowanie!=null)anulowanie.Cancel();}};
        PrzygotujKafelki();ZaladujDyski();PrzygotujNawigacje();gotowe=true;sekcje.SelectedIndex=0;
    }
    T Kontrolka<T>(string nazwa) where T:class{return Okno.FindName(nazwa) as T;}
    public void OtworzFolder(string sciezka){Nawiguj(sciezka);}
    async void ZaladujDyski(){try{var dyski=await Task.Run(()=>DriveInfo.GetDrives().Where(d=>d.DriveType==DriveType.Fixed||d.DriveType==DriveType.Removable).Select(d=>d.Name).ToArray());drzewo.Items.Clear();foreach(string sciezka in dyski)drzewo.Items.Add(Wezel(sciezka,sciezka.TrimEnd('\\'),false));}catch(Exception blad){stan.Text=blad.Message;}}
    TreeViewItem Wezel(string sciezka,string nazwa,bool systemowy){var wezel=new TreeViewItem {Header=nazwa,Tag=sciezka,Foreground=Program.Kolor(systemowy?"#7E8899":"#CAD4E5"),ToolTip=sciezka};wezel.Items.Add(new TreeViewItem {Header="Ładowanie…",Tag=null});wezel.Expanded+=async(s,e)=>{if(e.OriginalSource!=wezel)return;if(wezel.Items.Count==1&&((TreeViewItem)wezel.Items[0]).Tag==null){wezel.Items.Clear();await DzieciDrzewa(wezel,sciezka,0);}};wezel.Selected+=(s,e)=>{if(e.OriginalSource==wezel){OtworzFolder(sciezka);e.Handled=true;}};return wezel;}
    async Task DzieciDrzewa(TreeViewItem wezel,string sciezka,int od){try{var dzieci=await Task.Run(()=>new DirectoryInfo(sciezka).EnumerateDirectories().OrderBy(d=>d.Name,StringComparer.CurrentCultureIgnoreCase).Skip(od).Take(201).Select(d=>new object[]{d.FullName,d.Name,0}).ToList());foreach(var r in dzieci.Take(200))wezel.Items.Add(Wezel((string)r[0],(Convert.ToInt64(r[2])!=0?"🔒 ":"")+(string)r[1],Convert.ToInt64(r[2])!=0));if(dzieci.Count>200){var wiecej=new TreeViewItem {Header="Pokaż kolejne 200…"};wiecej.Selected+=async(s,e)=>{e.Handled=true;wezel.Items.Remove(wiecej);await DzieciDrzewa(wezel,sciezka,od+200);};wezel.Items.Add(wiecej);}}catch(Exception blad){stan.Text=blad.Message;}}
    bool WidokDuplikatow(){return tryb=="Potwierdzone duplikaty"||tryb=="Potencjalnie odzyskiwane miejsce";}
    void Kolumny(){WczytajUklad();if(!WidokDuplikatow()){ZbudujSzczegoly();return;}lista.RowHeight=48;lista.Columns.Clear();var szablon=(DataTemplate)XamlReader.Parse("<DataTemplate xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation'><StackPanel><TextBlock Text='{Binding Nazwa}' FontWeight='SemiBold' TextTrimming='CharacterEllipsis'/><TextBlock Text='{Binding Sciezka}' FontSize='10' Foreground='#8294B0' TextTrimming='CharacterEllipsis'/></StackPanel></DataTemplate>");lista.Columns.Add(new DataGridTemplateColumn {Header=WidokDuplikatow()?"ZAWARTOŚĆ / SHA-256":"NAZWA / ŚCIEŻKA",CellTemplate=szablon,Width=new DataGridLength(1,DataGridLengthUnitType.Star),MinWidth=180});DodajKolumne(WidokDuplikatow()?"ROZMIAR PLIKU":"ROZMIAR","RozmiarTekst",118);if(WidokDuplikatow()){DodajKolumne("LOKALIZACJE","PlikiTekst",90);DodajKolumne("KOPIE ŁĄCZNIE","ZajeteTekst",110);DodajKolumne("POTENCJAŁ","PotencjalTekst",110);}else{DodajKolumne("TYP","TypTekst",115);DodajKolumne("FORMAT","Rozszerzenie",75);DodajKolumne("UTWORZONO","UtworzenieTekst",110);DodajKolumne("MODYFIKACJA","DataTekst",140);DodajKolumne("LOKALIZACJA","Sciezka",280);DodajKolumne("DUPLIKAT","StatusDuplikatu",140);DodajKolumne("TAGI","Oznaczenia",240);}lista.ToolTip="Szczegóły i oznaczenia są w prawym panelu.";}
    void DodajKolumne(string naglowek,string pole,double szerokosc){lista.Columns.Add(new DataGridTextColumn {Header=naglowek,Binding=new Binding(pole),Width=szerokosc,CanUserSort=false});}
    List<Wiersz> PobierzSurowe(string wybranyTryb,string wybranyFolder,string filtr,bool pokaz,int numerStrony,int limit){using(var baza=new Baza(Program.Indeks,false)){
        var args=new List<object>();string sql;
        if(wybranyTryb=="Potwierdzone duplikaty"||wybranyTryb=="Potencjalnie odzyskiwane miejsce"){sql="SELECT id,sha256,rozmiar,lokalizacje,niezalezne,zajete,potencjal,niepewne FROM grupy_duplikatow WHERE (?='' OR sha256 LIKE ? OR EXISTS(SELECT 1 FROM lokalizacje_duplikatow l WHERE l.grupa=grupy_duplikatow.id AND l.sciezka LIKE ?)) ORDER BY potencjal DESC,id LIMIT ? OFFSET ?";return baza.Zapytaj(sql,filtr,"%"+filtr+"%","%"+filtr+"%",limit+1,numerStrony*limit).Select(Program.Grupa).ToList();}
        if(wybranyTryb=="Folder"){var dane=ZawartoscFolderu(baza,wybranyFolder,filtr,pokaz,limit+1,numerStrony*limit);return dane;}
        if(wybranyTryb=="Największe pliki"){var dane=baza.Zapytaj("SELECT p.sciezka,p.rozmiar,p.zmiana,p.typ,p.sha256 FROM pliki p WHERE (?=1 OR NOT EXISTS(SELECT 1 FROM widok_folderow f WHERE f.sciezka=p.folder AND f.systemowy=1)) AND (?='' OR p.sciezka LIKE ?) ORDER BY p.rozmiar DESC,p.id LIMIT ? OFFSET ?",pokaz?1:0,filtr,"%"+filtr+"%",limit+1,numerStrony*limit).Select(Program.Plik).ToList();return dane;}
        sql="SELECT "+Program.KolumnyFolderu+" FROM widok_folderow WHERE "+(pokaz?"1=1":"systemowy=0");
        if(wybranyTryb=="Folder"){sql+=" AND rodzic=?";args.Add(wybranyFolder);}else{sql+=" AND rodzic IS NOT NULL";}
        string sort="rozmiar DESC,sciezka";
        if(wybranyTryb=="Zgrywy telefonów")sql+=" AND (lower(sciezka) LIKE '%telefon%' OR lower(sciezka) LIKE '%fona%' OR lower(sciezka) LIKE '%redmi%' OR lower(sciezka) LIKE '%samsung%' OR lower(nazwa) IN ('dcim','camera'))";
        if(wybranyTryb=="Filmy"){sql+=" AND filmy>0";sort="filmy DESC,sciezka";}
        if(wybranyTryb=="Zdjęcia"){sql+=" AND zdjecia>0";sort="zdjecia DESC,sciezka";}
        if(wybranyTryb=="Archiwa i backupy")sql+=" AND (archiwa>0 OR sygnal=1)";
        if(wybranyTryb=="Foldery wymagające uwagi"){sql+=" AND (uwagi<>'' OR sygnal=1 OR duplikaty>0 OR rozmiar>=?)";args.Add((long)(Program.Ustawienia.bardzoDuzyFolderGiB*1073741824));}
        sql+=" AND (?='' OR nazwa LIKE ? OR sciezka LIKE ?) ORDER BY "+sort+" LIMIT ? OFFSET ?";args.Add(filtr);args.Add("%"+filtr+"%");args.Add("%"+filtr+"%");args.Add(limit+1);args.Add(numerStrony*limit);return baza.Zapytaj(sql,args.ToArray()).Select(Program.Folder).ToList();
    }}
    async void OdswiezListe(){if(edycjaNazwy!=null&&!zatwierdzanie)return;var zaznaczeniePrzed=lista.SelectedItems.Cast<Wiersz>().Select(w=>w.Sciezka).ToList();int obecna=++wersja;string t=tryb,f=folder,filtr=szukaj.Text;int n=strona;bool pokaz=systemowe.IsChecked==true;naglowek.Text=t=="Folder"?(Path.GetFileName(f.TrimEnd('\\'))==""?f:Path.GetFileName(f.TrimEnd('\\'))):t;sciezkaWidoku.Text=t=="Folder"?f:"Indeks wszystkich dysków";PokazBreadcrumb();opis.Text=t=="Folder"?"Eksplorator • bieżąca zawartość dysku • statystyki z indeksu":WidokDuplikatow()?"Pełne SHA-256 • potencjał po pozostawieniu jednej kopii":"Rozmiary rekursywne • nie sumuj rodzica z potomkami";Kolumny();stan.Text=t=="Folder"?"Odczytywanie folderu…":"Wczytywanie strony indeksu…";
        try{var dane=await Task.Run(()=>Pobierz(t,f,filtr,pokaz,n));if(obecna!=wersja)return;bool jestDalej=dane.Count>Program.Ustawienia.rozmiarStrony;ostatnie=dane.Take(Program.Ustawienia.rozmiarStrony).ToList();zaznaczone.Clear();kotwica=null;lista.ItemsSource=ostatnie;foreach(var wybrany in ostatnie.Where(w=>zaznaczeniePrzed.Contains(w.Sciezka)))lista.SelectedItems.Add(wybrany);zaznaczone=new HashSet<Wiersz>(lista.SelectedItems.Cast<Wiersz>());PokazWybranyWidok();await UzupelnijDaty(ostatnie,obecna);if(obecna!=wersja)return;poprzednia.IsEnabled=n>0;nastepna.IsEnabled=jestDalej;numer.Text="Strona "+(n+1);stan.Text=ostatnie.Count+(t=="Folder"?" elementów • system plików • ":" wierszy • indeks lokalny • ")+(zajety?"trwa skan w tle":"bez ponownego skanowania dysków");if(ostatnie.Count>0){if(lista.SelectedItem==null)lista.SelectedIndex=0;}else{szczegoly.Children.Clear();szczegoly.Children.Add(Program.Tekst("Brak elementów w tym widoku.",18,"#ADB9CD"));if(t=="Folder")szczegoly.Children.Add(Program.Tekst("Folder jest pusty lub filtr nie pasuje do jego zawartości.",13,"#8294B0"));else using(var baza=new Baza(Program.Indeks,false)){if(Convert.ToInt64(baza.Wartosc("SELECT (SELECT count(*) FROM pliki)+(SELECT count(*) FROM widok_folderow)"))==0){stan.Text="Pusty indeks — wybierz folder do pierwszego skanu.";szczegoly.Children.Add(Program.Tekst("Rozpocznij od wybrania folderu lub dysku. Skan zapisze wyniki w lokalnym indeksie aplikacji.",13,"#8294B0"));szczegoly.Children.Add(Program.Przycisk("Wybierz folder do skanowania…",OknoSkanowania));}}}wczytanaWersja=obecna;PrzywrocStan();}catch(Exception blad){stan.Text=blad.Message;}}
    void DodajSzczegol(string etykieta,string wartosc){szczegoly.Children.Add(Program.Tekst(etykieta.ToUpperInvariant(),10,"#7D91B1"));szczegoly.Children.Add(Program.Tekst(wartosc,15,"#E7ECF4"));}
    async void PokazGrupeDuplikatow(Wiersz w){stronyLokalizacji.Clear();szczegoly.Children.Clear();szczegoly.Children.Add(Program.Tekst(w.Nazwa,21,"#EEF4FF"));szczegoly.Children.Add(new TextBox {Text=w.Sciezka,IsReadOnly=true,TextWrapping=TextWrapping.Wrap,BorderThickness=new Thickness(0),Background=Brushes.Transparent,Foreground=Program.Kolor("#91A8CD"),Padding=new Thickness(0,8,0,8)});
        if(!String.IsNullOrEmpty(w.Oznaczenia)){var znaczniki=new WrapPanel();foreach(string tag in w.Oznaczenia.Split(new[]{" · "},StringSplitOptions.RemoveEmptyEntries)){string kolor=tag.Contains("SYSTEM")?"#445063":tag.Contains("DUPLIK")?"#214E6E":tag.Contains("UWAGI")||tag.Contains("STARE")?"#654D29":"#30435B";znaczniki.Children.Add(new Border {Background=Program.Kolor(kolor),CornerRadius=new CornerRadius(4),Padding=new Thickness(7,4,7,4),Margin=new Thickness(0,0,5,6),Child=Program.Tekst(tag,10,"#D5E4FA")});}szczegoly.Children.Add(znaczniki);}
        DodajSzczegol(w.Rodzaj=="duplikat"?"Rozmiar jednego pliku":"Rozmiar",w.RozmiarTekst);
        if(w.Rodzaj=="duplikat"){DodajSzczegol("Lokalizacje",w.PlikiTekst);DodajSzczegol("Niezależne kopie łącznie",w.ZajeteTekst);DodajSzczegol("Teoretycznie do odzyskania",w.PotencjalTekst);szczegoly.Children.Add(Program.Tekst("Wynik logiczny, z odjęciem rozpoznanych hardlinków. Kopie mogą być celowym backupem. Nie wybrano niczego do kasowania.",12,"#9BADCA"));if(w.Niepewne>0)szczegoly.Children.Add(Program.Tekst("Część tożsamości fizycznych wymaga ponownej weryfikacji — potencjał jest górnym oszacowaniem.",12,"#F0BB6D"));szczegoly.Children.Add(Program.Przycisk("Porównaj lokalizacje",()=>Porownaj(w)));await Lokalizacje(w,0);return;}
        DodajSzczegol("Ostatnia modyfikacja",w.DataTekst);if(w.Rodzaj=="folder"){DodajSzczegol("Pliki w poddrzewie",w.PlikiTekst);DodajSzczegol("Podfoldery w poddrzewie",w.PodfolderyTekst);Sklad(w);if(w.Duplikaty>0)DodajSzczegol("Zawartość w grupach duplikatów",Program.Rozmiar(w.Duplikaty));}
        if(!String.IsNullOrEmpty(w.Uwagi))szczegoly.Children.Add(Program.Tekst(w.Uwagi,12,"#F0BB6D"));
        string lokalizacja=w.Rodzaj=="folder"?w.Sciezka:Path.GetDirectoryName(w.Sciezka);szczegoly.Children.Add(Program.Przycisk("Otwórz folder",()=>OtworzFolder(lokalizacja)));szczegoly.Children.Add(Program.Przycisk("Otwórz w Eksploratorze Windows",()=>Program.Eksplorator(lokalizacja)));szczegoly.Children.Add(Program.Przycisk("Kopiuj ścieżkę",()=>Program.Kopiuj(w.Sciezka)));szczegoly.Children.Add(Program.Przycisk("Porównaj lokalizacje",()=>PorownajWybrany()));UzupelnijPanel(w);
    }
    void Sklad(Wiersz w){string[] nazwy={"Filmy","Zdjęcia","Dokumenty","Archiwa","Pozostałe"};string[] kolory={"#7E98FA","#54C3AA","#D3B66B","#B389DF","#62748F"};szczegoly.Children.Add(Program.Tekst("UDZIAŁ W ROZMIARZE",10,"#7D91B1"));var pasek=new Grid {Height=10,Margin=new Thickness(0,10,0,12)};for(int i=0;i<5;i++){pasek.ColumnDefinitions.Add(new ColumnDefinition {Width=new GridLength(Math.Max(0,w.Typy[i]),GridUnitType.Star)});var pole=new Border {Background=Program.Kolor(kolory[i])};Grid.SetColumn(pole,i);pasek.Children.Add(pole);}szczegoly.Children.Add(pasek);for(int i=0;i<5;i++)szczegoly.Children.Add(Program.Tekst(nazwy[i]+"  "+(w.Rozmiar>0?(100.0*w.Typy[i]/w.Rozmiar).ToString("N1"):"0")+"%  ·  "+Program.Rozmiar(w.Typy[i]),12,kolory[i]));}
    async Task Lokalizacje(Wiersz w,int od){if(!stronyLokalizacji.Add(od))return;int aktualnaInformacja=wersjaInformacji;var pozycje=await Task.Run(()=>{using(var baza=new Baza(Program.Indeks,false))return baza.Zapytaj("SELECT sciezka,folder FROM lokalizacje_duplikatow WHERE grupa=? ORDER BY sciezka LIMIT 101 OFFSET ?",w.Grupa,od);});if(lista.SelectedItem!=w||aktualnaInformacja!=wersjaInformacji||!Kafelki.Ustawienia.PanelSzczegolow)return;szczegoly.Children.Add(Program.Tekst("LOKALIZACJE "+(od+1)+"–"+(od+Math.Min(100,pozycje.Count)),10,"#7D91B1"));foreach(var p in pozycje.Take(100)){string sciezka=(string)p[0],f=(string)p[1];var ramka=new StackPanel {Margin=new Thickness(0,5,0,10)};ramka.Children.Add(Program.Tekst(sciezka,11,"#BDD3F4"));var przyciski=new WrapPanel();przyciski.Children.Add(Program.Przycisk("Folder",()=>OtworzFolder(f)));przyciski.Children.Add(Program.Przycisk("Eksplorator",()=>Program.Eksplorator(f)));przyciski.Children.Add(Program.Przycisk("Ścieżka",()=>Program.Kopiuj(sciezka)));ramka.Children.Add(przyciski);szczegoly.Children.Add(ramka);}if(pozycje.Count>100){var przycisk=Program.Przycisk("Pokaż kolejne lokalizacje…",async()=>await Lokalizacje(w,od+100));szczegoly.Children.Add(przycisk);}}
    async void PorownajWybrany(){var w=lista.SelectedItem as Wiersz;if(w==null)return;if(w.Rodzaj=="duplikat"){Porownaj(w);return;}var grupy=await Task.Run(()=>{using(var baza=new Baza(Program.Indeks,false)){if(w.Rodzaj=="plik")return baza.Zapytaj("SELECT g.* FROM grupy_duplikatow g JOIN lokalizacje_duplikatow l ON g.id=l.grupa WHERE l.sciezka=? LIMIT 1",w.Sciezka);return baza.Zapytaj("SELECT DISTINCT g.* FROM grupy_duplikatow g JOIN lokalizacje_duplikatow l ON g.id=l.grupa WHERE l.folder=? OR l.sciezka LIKE ? ESCAPE '^' ORDER BY g.potencjal DESC LIMIT 1",w.Sciezka,Program.Prefiks(w.Sciezka));}});if(grupy.Count>0)Porownaj(Program.Grupa(grupy[0]));else MessageBox.Show("W tym zakresie indeks nie zawiera potwierdzonej grupy duplikatów.","Porównanie");}
    async void Porownaj(Wiersz w){var lokalizacje=await Task.Run(()=>{using(var baza=new Baza(Program.Indeks,false))return baza.Zapytaj("SELECT DISTINCT folder FROM lokalizacje_duplikatow WHERE grupa=? ORDER BY folder",w.Grupa).Select(r=>(string)r[0]).ToList();});if(lokalizacje.Count==0)return;var porownanie=new Porownanie(lokalizacje,w.Hash,w.Rozmiar);porownanie.Okno.Owner=Okno;porownanie.Okno.Show();}
    void OknoSkanowania(){if(zajety){MessageBox.Show("Skan już trwa. Możesz go anulować w oknie skanowania.");return;}var okno=new Window {Owner=Okno,Title="Odśwież skan — tylko odczyt źródeł",Width=660,Height=420,Background=Program.Kolor("#181E28"),Foreground=Brushes.White,WindowStartupLocation=WindowStartupLocation.CenterOwner};var panel=new StackPanel {Margin=new Thickness(24)};okno.Content=panel;panel.Children.Add(Program.Tekst("Odśwież indeks",23,"#EDF3FF"));panel.Children.Add(Program.Tekst("Aktualizowana jest wyłącznie baza aplikacji. Pliki źródłowe nie są usuwane, przenoszone ani nadpisywane. Pełne hashe dotyczą nowych i zmienionych kandydatów. Potwierdzanie może odczytać pasujące pliki z innych lokalizacji indeksu.",13,"#9EB0CC"));var pole=new TextBox {Text=folder!=""?folder:(lista.SelectedItem is Wiersz&&((Wiersz)lista.SelectedItem).Rodzaj=="folder"?((Wiersz)lista.SelectedItem).Sciezka:"C:\\"),Margin=new Thickness(0,16,0,6)};panel.Children.Add(pole);panel.Children.Add(Program.Przycisk("Wybierz folder…",()=>{using(var dialog=new System.Windows.Forms.FolderBrowserDialog {ShowNewFolderButton=false,SelectedPath=pole.Text})if(dialog.ShowDialog()==System.Windows.Forms.DialogResult.OK)pole.Text=dialog.SelectedPath;}));var hashe=new CheckBox {Content="Potwierdzaj nowe duplikaty pełnym SHA-256",IsChecked=Program.Ustawienia.pelneHashePrzyOdswiezaniu,Margin=new Thickness(0,10,0,10)};panel.Children.Add(hashe);var postep=Program.Tekst("Wybierz zakres.",12,"#92AACF");panel.Children.Add(postep);var przyciski=new WrapPanel();panel.Children.Add(przyciski);var anuluj=Program.Przycisk("Anuluj skan",()=>{if(anulowanie!=null)anulowanie.Cancel();});anuluj.IsEnabled=false;
        Action<List<string>> uruchom=async zakresy=>{if(zajety)return;zajety=true;anulowanie=new CancellationTokenSource();anuluj.IsEnabled=true;foreach(Button p in przyciski.Children)p.IsEnabled=p==anuluj;try{var wyniki=await Task.Run(()=>{var wynikiSkanu=new List<string>();foreach(var zakres in zakresy){anulowanie.Token.ThrowIfCancellationRequested();try{var wynik=Skaner.Skanuj(zakres,hashe.Dispatcher.Invoke(()=>hashe.IsChecked==true),anulowanie.Token,tekst=>Okno.Dispatcher.BeginInvoke(new Action(()=>{postep.Text=tekst;stan.Text=tekst;})));wynikiSkanu.Add(wynik);}catch(OperationCanceledException){throw;}catch(Exception blad){wynikiSkanu.Add(zakres+": "+blad.Message);}}return wynikiSkanu;});postep.Text=String.Join(Environment.NewLine,wyniki);ZaladujDyski();OdswiezListe();}catch(OperationCanceledException){postep.Text="Anulowano. Nieukończony zakres nie zastąpił poprzedniego indeksu.";}catch(Exception blad){postep.Text=blad.Message;}finally{zajety=false;anuluj.IsEnabled=false;foreach(Button p in przyciski.Children)if(p!=anuluj)p.IsEnabled=true;}};
        przyciski.Children.Add(Program.Przycisk("Skanuj folder",()=>uruchom(new List<string>{pole.Text})));przyciski.Children.Add(Program.Przycisk("Skanuj dysk",()=>{try{uruchom(new List<string>{Path.GetPathRoot(Path.GetFullPath(pole.Text))});}catch(Exception blad){postep.Text=blad.Message;}}));przyciski.Children.Add(Program.Przycisk("Wszystkie dyski",()=>{uruchom(DriveInfo.GetDrives().Where(d=>d.IsReady&&d.DriveType==DriveType.Fixed).Select(d=>d.Name).ToList());}));przyciski.Children.Add(anuluj);okno.Closing+=(s,e)=>{if(zajety){e.Cancel=true;postep.Text="Najpierw anuluj skan lub poczekaj na jego zakończenie.";}};okno.Show();
    }
    public void ZapiszZrzuty(string katalog){
        Directory.CreateDirectory(katalog);Oczekuj(()=>ostatnie.Count>0);double skalaDuzych=Kafelki.Ustawienia.SkalaDuzych;var zapamietane=Kafelki.Ustawienia.Widoki.ToDictionary(p=>p.Key,p=>p.Value,StringComparer.OrdinalIgnoreCase);
        try{
            Kafelki.Ustawienia.SkalaDuzych=100;Kafelki.Ustawienia.Widoki[KluczWidoku()]="Duże kafelki";PokazWybranyWidok();Renderuj(Okno,Path.Combine(katalog,"01-foldery.png"));
            skalaKafelkow.Value=75;PokazWybranyWidok();Renderuj(Okno,Path.Combine(katalog,"07-skala-75.png"));
            skalaKafelkow.Value=125;PokazWybranyWidok();Renderuj(Okno,Path.Combine(katalog,"08-skala-125.png"));
            Kafelki.Ustawienia.SkalaDuzych=100;
            Kafelki.Ustawienia.Widoki[KluczWidoku()]="Kompaktowe kafelki";PokazWybranyWidok();Renderuj(Okno,Path.Combine(katalog,"04-kompaktowe.png"));
            Kafelki.Ustawienia.Widoki[KluczWidoku()]="Lista szczegółowa";PokazWybranyWidok();Renderuj(Okno,Path.Combine(katalog,"05-lista.png"));
            var wyglad=new OknoWygladu(Okno,()=>{},true);Renderuj(wyglad.Okno,Path.Combine(katalog,"06-personalizacja.png"));wyglad.Okno.Close();
            sekcje.SelectedItem="Największe pliki";szukaj.Text=".jpg";opoznienie.Stop();OdswiezListe();Oczekuj(()=>ostatnie.Count>0&&ostatnie[0].Rodzaj=="plik"&&Kafelki.Kategoria(ostatnie[0])=="Zdjęcie");
            foreach(var element in ostatnie.Take(12)){var przygotowanie=Task.Run(()=>Kafelki.Metadane(element,CancellationToken.None));Oczekuj(()=>przygotowanie.IsCompleted);element.MetadanePodgladu=przygotowanie.GetAwaiter().GetResult();}
            wyborWidoku.SelectedItem="Duże kafelki";skalaKafelkow.Value=100;PokazWybranyWidok();Renderuj(Okno,Path.Combine(katalog,"09-zdjecia.png"));
            szukaj.Text=".mp4";opoznienie.Stop();OdswiezListe();Oczekuj(()=>ostatnie.Count>0&&ostatnie[0].Rodzaj=="plik"&&Kafelki.Kategoria(ostatnie[0])=="Film");
            foreach(var element in ostatnie.Take(12)){var przygotowanie=Task.Run(()=>Kafelki.Metadane(element,CancellationToken.None));Oczekuj(()=>przygotowanie.IsCompleted);element.MetadanePodgladu=przygotowanie.GetAwaiter().GetResult();}
            wyborWidoku.SelectedItem="Duże kafelki";skalaKafelkow.Value=100;PokazWybranyWidok();Renderuj(Okno,Path.Combine(katalog,"10-filmy.png"));
            szukaj.Text="";opoznienie.Stop();sekcje.SelectedItem="Potwierdzone duplikaty";Oczekuj(()=>ostatnie.Count>0&&ostatnie[0].Rodzaj=="duplikat");Renderuj(Okno,Path.Combine(katalog,"02-duplikaty.png"));
            using(var baza=new Baza(Program.Indeks,false)){var w=ostatnie[0];var lok=baza.Zapytaj("SELECT DISTINCT folder FROM lokalizacje_duplikatow WHERE grupa=? ORDER BY folder",w.Grupa).Select(r=>(string)r[0]).ToList();var porownanie=new Porownanie(lok,w.Hash,w.Rozmiar);porownanie.WczytajDoTestu();Renderuj(porownanie.Okno,Path.Combine(katalog,"03-porownanie.png"));porownanie.Okno.Close();}
            File.WriteAllText(Path.Combine(katalog,"test-ui.txt"),"Załadowano XAML, duże i kompaktowe kafelki, listę szczegółową, personalizację, duplikaty i obie strony porównania. Limit strony: "+Program.Ustawienia.rozmiarStrony+". Renderowanie nie potwierdza ręcznych interakcji, płynności GPU ani działania wszystkich kodeków.",Encoding.UTF8);
        }finally{Kafelki.Ustawienia.SkalaDuzych=skalaDuzych;Kafelki.Ustawienia.Widoki=zapamietane;}
    }
    public static void Oczekuj(Func<bool> warunek){var zegar=Stopwatch.StartNew();while(!warunek()){if(zegar.Elapsed.TotalSeconds>30)throw new TimeoutException("Widok nie został wczytany.");var ramka=new DispatcherFrame();Dispatcher.CurrentDispatcher.BeginInvoke(DispatcherPriority.Background,new Action(()=>ramka.Continue=false));Dispatcher.PushFrame(ramka);Thread.Sleep(10);}}
    public static void Renderuj(Window okno,string sciezka){
        okno.ShowActivated=false;okno.ShowInTaskbar=false;okno.Opacity=0;okno.WindowStyle=WindowStyle.None;
        if(!okno.IsVisible)okno.Show();
        var zawartosc=(FrameworkElement)okno.Content;var panel=zawartosc as Panel;if(panel!=null)panel.Background=okno.Background;
        for(int i=0;i<4;i++){okno.UpdateLayout();var ramka=new DispatcherFrame();Dispatcher.CurrentDispatcher.BeginInvoke(DispatcherPriority.ApplicationIdle,new Action(()=>ramka.Continue=false));Dispatcher.PushFrame(ramka);}
        int szerokosc=(int)Math.Ceiling(zawartosc.ActualWidth),wysokosc=(int)Math.Ceiling(zawartosc.ActualHeight);
        var obraz=new RenderTargetBitmap(szerokosc,wysokosc,96,96,PixelFormats.Pbgra32);obraz.Render(zawartosc);var koder=new PngBitmapEncoder();koder.Frames.Add(BitmapFrame.Create(obraz));using(var plik=File.Create(sciezka))koder.Save(plik);
    }

}
public sealed class Porownanie {
    public Window Okno;List<string> lokalizacje;string hash;long rozmiar;int zaladowane;
    public Porownanie(List<string> sciezki,string skrot,long bajty){lokalizacje=sciezki;hash=skrot;rozmiar=bajty;Okno=new Window {Title="Porównaj lokalizacje — Mapa dysków",Width=1380,Height=780,MinWidth=950,MinHeight=550,Background=Program.Kolor("#11151D"),Foreground=Brushes.White,FontFamily=new FontFamily("Segoe UI"),WindowStartupLocation=WindowStartupLocation.CenterOwner};Okno.Resources=Program.Zasoby;var uklad=new Grid {Margin=new Thickness(20),Background=Program.Kolor("#11151D")};uklad.RowDefinitions.Add(new RowDefinition {Height=GridLength.Auto});uklad.RowDefinitions.Add(new RowDefinition());Okno.Content=uklad;var opis=Program.Tekst("Porównanie lokalizacji  ·  "+Program.Rozmiar(bajty)+"  ·  SHA-256 "+skrot.Substring(0,16)+"…\nPodświetlone pliki należą do wybranej grupy. Foldery i pliki są przeglądane z indeksu, po 200 pozycji na stronę.",15,"#B5CBE9");uklad.Children.Add(opis);var strony=new Grid {Margin=new Thickness(0,15,0,0)};strony.ColumnDefinitions.Add(new ColumnDefinition());strony.ColumnDefinitions.Add(new ColumnDefinition {Width=new GridLength(18)});strony.ColumnDefinitions.Add(new ColumnDefinition());Grid.SetRow(strony,1);uklad.Children.Add(strony);var lewa=Panel("LEWA LOKALIZACJA",sciezki[0]);var prawa=Panel("PRAWA LOKALIZACJA",sciezki.Count>1?sciezki[1]:sciezki[0]);strony.Children.Add(lewa);Grid.SetColumn(prawa,2);strony.Children.Add(prawa);}
    FrameworkElement Panel(string nazwa,string poczatkowa){var panel=new Grid {Background=Program.Kolor("#181E28"),Margin=new Thickness(2)};panel.RowDefinitions.Add(new RowDefinition {Height=GridLength.Auto});panel.RowDefinitions.Add(new RowDefinition());panel.RowDefinitions.Add(new RowDefinition {Height=GridLength.Auto});var gora=new StackPanel {Margin=new Thickness(15)};panel.Children.Add(gora);gora.Children.Add(Program.Tekst(nazwa,11,"#8AA8D0"));var wybor=new ComboBox {ItemsSource=lokalizacje,SelectedItem=poczatkowa,IsEditable=true,Text=poczatkowa,Foreground=Brushes.Black};gora.Children.Add(wybor);var sciezka=new TextBox {Text=poczatkowa,IsReadOnly=true,TextWrapping=TextWrapping.Wrap,Background=Brushes.Transparent,Foreground=Program.Kolor("#E4EDFB"),BorderThickness=new Thickness(0)};gora.Children.Add(sciezka);var przyciski=new WrapPanel();gora.Children.Add(przyciski);var lista=new DataGrid {AutoGenerateColumns=false,IsReadOnly=true,CanUserAddRows=false,CanUserDeleteRows=false,EnableRowVirtualization=true,EnableColumnVirtualization=true,Background=Program.Kolor("#181E28"),Foreground=Program.Kolor("#E4EDFB"),RowBackground=Program.Kolor("#202C3C"),AlternatingRowBackground=Program.Kolor("#26364A"),HeadersVisibility=DataGridHeadersVisibility.Column,GridLinesVisibility=DataGridGridLinesVisibility.None,Margin=new Thickness(12),SelectionMode=DataGridSelectionMode.Single};VirtualizingPanel.SetVirtualizationMode(lista,VirtualizationMode.Recycling);lista.Columns.Add(new DataGridTextColumn {Header="Nazwa",Binding=new Binding("Nazwa"),Width=new DataGridLength(1,DataGridLengthUnitType.Star)});lista.Columns.Add(new DataGridTextColumn {Header="Rozmiar",Binding=new Binding("RozmiarTekst"),Width=110});lista.Columns.Add(new DataGridTextColumn {Header="Oznaczenie",Binding=new Binding("Oznaczenia"),Width=140});var styl=new Style(typeof(DataGridRow));var wyzwalacz=new DataTrigger {Binding=new Binding("Hash"),Value=hash};wyzwalacz.Setters.Add(new Setter(Control.BackgroundProperty,Program.Kolor("#255176")));styl.Triggers.Add(wyzwalacz);lista.RowStyle=styl;Grid.SetRow(lista,1);panel.Children.Add(lista);int strona=0,wersja=0;string folder=poczatkowa;var dol=new WrapPanel {Margin=new Thickness(12)};var numer=Program.Tekst("",12,"#A5BFDF");Grid.SetRow(dol,2);panel.Children.Add(dol);Button dalej=null,wstecz=null;
        Action<string> wczytaj=async f=>{folder=f;sciezka.Text=f;int aktualna=++wersja,n=strona;var dane=await Task.Run(()=>{using(var baza=new Baza(Program.Indeks,false)){var wynik=new List<Wiersz>();long liczbaFolderow=Convert.ToInt64(baza.Wartosc("SELECT count(*) FROM widok_folderow WHERE rodzic=?",f));
foreach(var r in baza.Zapytaj("SELECT "+Program.KolumnyFolderu+" FROM widok_folderow WHERE rodzic=? ORDER BY nazwa LIMIT 201 OFFSET ?",f,n*200))wynik.Add(Program.Folder(r));
if(wynik.Count<201){int miejsce=201-wynik.Count;long odPlikow=Math.Max(0,n*200-liczbaFolderow);foreach(var r in baza.Zapytaj("SELECT sciezka,rozmiar,zmiana,typ,sha256 FROM pliki WHERE folder=? ORDER BY CASE WHEN sha256=? THEN 0 ELSE 1 END,sciezka LIMIT ? OFFSET ?",f,hash,miejsce,odPlikow))wynik.Add(Program.Plik(r));}
return wynik;}});if(aktualna!=wersja)return;lista.ItemsSource=dane.Take(200).ToList();dalej.IsEnabled=dane.Count>200;wstecz.IsEnabled=n>0;numer.Text="Strona "+(n+1)+" • foldery i pliki";zaladowane++;};
        przyciski.Children.Add(Program.Przycisk("Otwórz folder",()=>{strona=0;wczytaj(wybor.Text);}));przyciski.Children.Add(Program.Przycisk("Eksplorator Windows",()=>Program.Eksplorator(folder)));przyciski.Children.Add(Program.Przycisk("Kopiuj ścieżkę",()=>Program.Kopiuj(folder)));przyciski.Children.Add(Program.Przycisk("↑",()=>{var rodzic=Path.GetDirectoryName(folder.TrimEnd('\\'));if(!String.IsNullOrEmpty(rodzic)){if(rodzic.EndsWith(":"))rodzic+="\\";strona=0;wczytaj(rodzic);}}));wstecz=Program.Przycisk("‹",()=>{strona--;wczytaj(folder);});dalej=Program.Przycisk("›",()=>{strona++;wczytaj(folder);});dol.Children.Add(wstecz);dol.Children.Add(numer);dol.Children.Add(dalej);wybor.SelectionChanged+=(s,e)=>{if(wybor.SelectedItem!=null){strona=0;wczytaj(Convert.ToString(wybor.SelectedItem));}};lista.MouseDoubleClick+=(s,e)=>{var w=lista.SelectedItem as Wiersz;if(w!=null&&w.Rodzaj=="folder"){strona=0;wczytaj(w.Sciezka);}};Action<string,string> zmianaNazwy=(stara,nowa)=>{folder=OperacjePlikowe.Podmien(folder,stara,nowa);lokalizacje=lokalizacje.Select(p=>OperacjePlikowe.Podmien(p,stara,nowa)).ToList();wybor.ItemsSource=lokalizacje;wybor.SelectedItem=folder;wybor.Text=folder;wczytaj(folder);};OperacjePlikowe.ZmienionoNazwe+=zmianaNazwy;Okno.Closed+=(s,e)=>OperacjePlikowe.ZmienionoNazwe-=zmianaNazwy;wczytaj(poczatkowa);return panel;}
    public void WczytajDoTestu(){OknoGlowne.Oczekuj(()=>zaladowane>=2);}
}
}
