using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Threading;

namespace MapaDyskow {
public static class TestyOperacji {
    public static void Wymagaj(bool warunek,string opis){if(!warunek)throw new InvalidOperationException("TEST OPERACJI: "+opis);}
    static void Konflikt(Action akcja,string opis){bool odmowa=false;try{akcja();}catch(IOException){odmowa=true;}Wymagaj(odmowa,opis);}
    public static void Uruchom(string katalog,List<string> wyniki){
        string korzen=Path.Combine(katalog,"operacje-tymczasowe");Directory.CreateDirectory(korzen);
        string plik=Path.Combine(korzen,"foto.jpg");File.WriteAllBytes(plik,new byte[]{1,2,3,4});File.WriteAllBytes(Path.Combine(korzen,"kopia.jpg"),new byte[]{1,2,3,4});
        Skaner.Skanuj(korzen,true,CancellationToken.None,s=>{});string hash;using(var baza=new Baza(Program.Indeks,false))hash=Convert.ToString(baza.Wartosc("SELECT sha256 FROM pliki WHERE sciezka=?",plik));
        Wymagaj(hash.Length==64,"Fixture SHA-256");
        foreach(string nazwa in new[]{"a\\b","a/b","a:b","a*b","a?b","a\"b","a<b","a>b","a|b","CON","con.txt","PRN","AUX","NUL","COM1","COM9.txt","LPT1","LPT9","x.","x ","",new string('a',256)})Wymagaj(OperacjePlikowe.Waliduj(nazwa)!="","Walidacja: "+nazwa);
        Wymagaj(OperacjePlikowe.Waliduj("Zdjęcia 2025")==""&&OperacjePlikowe.Waliduj("COM10")=="","Poprawna nazwa");
        Wymagaj(OperacjePlikowe.DlugoscZaznaczenia("IMG_20230604_103544.jpg",true)==19,"Zaznaczenie bez rozszerzenia");Wymagaj(OperacjePlikowe.ZmieniaRozszerzenie("foto.jpg","foto.png")&&!OperacjePlikowe.ZmieniaRozszerzenie("foto.jpg","Foto.JPG"),"Zmiana rozszerzenia");
        string pierwszy=OperacjePlikowe.NowyFolder(korzen),drugi=OperacjePlikowe.NowyFolder(korzen);Wymagaj(Directory.Exists(pierwszy)&&Path.GetFileName(pierwszy)=="Nowy folder"&&Path.GetFileName(drugi)=="Nowy folder (2)","Tworzenie i numerowanie");
        string dziecko=OperacjePlikowe.NowyFolder(pierwszy);File.WriteAllText(Path.Combine(dziecko,"plik.txt"),"treść");OperacjePlikowe.OdswiezFolder(dziecko);
        var historia=new HistoriaLokalizacji();historia.Dodaj(new StanLokalizacji {Sciezka=korzen});historia.Dodaj(new StanLokalizacji {Sciezka=pierwszy,Scroll=55,Strona=2,Widok="Kompaktowe kafelki",SkalaKompaktowych=75});historia.Dodaj(new StanLokalizacji {Sciezka=dziecko,Zaznaczenie=Path.Combine(dziecko,"plik.txt")});
        Wymagaj(historia.Przejdz(-1).Scroll==55&&historia.Dalej,"Back i lekki stan scrolla");Wymagaj(historia.Przejdz(1).Sciezka==dziecko,"Forward");historia.Przejdz(-1);historia.Dodaj(new StanLokalizacji {Sciezka=drugi});Wymagaj(!historia.Dalej&&historia.Przejdz(1)==null,"Wyczyszczenie forward");historia.Dodaj(new StanLokalizacji {Sciezka=dziecko,Zaznaczenie=Path.Combine(dziecko,"plik.txt")});
        string nowy=OperacjePlikowe.ZmienNazwe(pierwszy,"Album",true);historia.ZmienSciezki(pierwszy,nowy);string nowyPotomek=Path.Combine(nowy,Path.GetFileName(dziecko));Wymagaj(File.ReadAllText(Path.Combine(nowyPotomek,"plik.txt"))=="treść"&&historia.Wpisy.Last().Sciezka==nowyPotomek&&historia.Wpisy.Last().Zaznaczenie==Path.Combine(nowyPotomek,"plik.txt"),"Folder, potomkowie i historia po rename");
        using(var baza=new Baza(Program.Indeks,false)){Wymagaj(Convert.ToInt64(baza.Wartosc("SELECT count(*) FROM widok_folderow WHERE sciezka=?",pierwszy))==0&&Convert.ToInt64(baza.Wartosc("SELECT count(*) FROM pliki WHERE folder=?",nowyPotomek))==1,"Indeks potomków");Wymagaj(Convert.ToInt64(baza.Wartosc("SELECT podfoldery FROM widok_folderow WHERE sciezka=?",korzen))==3,"Dane rodzica po create/rename");}
        long hashowania=Skaner.LiczbaHashowan;
        string zmieniony=OperacjePlikowe.ZmienNazwe(plik,"Foto.jpg",false);Wymagaj(File.Exists(zmieniony)&&new DirectoryInfo(korzen).GetFiles().Count(w=>w.Name=="Foto.jpg")==1,"Rename wyłącznie case");
        zmieniony=OperacjePlikowe.ZmienNazwe(zmieniony,"wakacje.jpg",false);using(var baza=new Baza(Program.Indeks,false)){Wymagaj(Convert.ToString(baza.Wartosc("SELECT sha256 FROM pliki WHERE sciezka=?",zmieniony))==hash,"Zachowany hash");Wymagaj(Convert.ToInt64(baza.Wartosc("SELECT count(*) FROM lokalizacje_duplikatow WHERE sciezka=?",zmieniony))==1,"Ścieżka duplikatu");}
        Konflikt(()=>OperacjePlikowe.ZmienNazwe(zmieniony,"kopia.jpg",false),"Konflikt pliku");Konflikt(()=>OperacjePlikowe.ZmienNazwe(nowy,Path.GetFileName(drugi),true),"Konflikt folderu");Konflikt(()=>OperacjePlikowe.ZmienNazwe(zmieniony,Path.GetFileName(drugi),false),"Konflikt plik/folder");Wymagaj(File.ReadAllBytes(zmieniony).SequenceEqual(new byte[]{1,2,3,4})&&Directory.Exists(drugi),"Brak nadpisania lub utraty danych");
        string zewnetrzny=Path.Combine(korzen,"zewnetrzny.txt");File.WriteAllText(zewnetrzny,"F5");OperacjePlikowe.OdswiezFolder(korzen);using(var baza=new Baza(Program.Indeks,false)){Wymagaj(Convert.ToInt64(baza.Wartosc("SELECT count(*) FROM pliki WHERE sciezka=?",zewnetrzny))==1,"F5 nowe dane");Wymagaj(Convert.ToString(baza.Wartosc("SELECT sha256 FROM pliki WHERE sciezka=?",zmieniony))==hash,"F5 zachowuje hash niezmienionego pliku");Wymagaj(Convert.ToString(baza.Wartosc("PRAGMA quick_check"))=="ok","Integralność");}
        Wymagaj(Skaner.LiczbaHashowan==hashowania,"Rename i F5 nie uruchamiają hashowania");
        string obraz=Path.Combine(korzen,"cache.png");File.Copy(Path.Combine(katalog,"dane-testowe","album zdjęć","miniatura.png"),obraz);OperacjePlikowe.OdswiezFolder(korzen);
        var wiersz=new Wiersz {Rodzaj="plik",Sciezka=obraz,Rozmiar=new FileInfo(obraz).Length,Zmiana=(File.GetLastWriteTimeUtc(obraz)-Program.Epoka).TotalSeconds};var miniatura=Kafelki.Metadane(wiersz,CancellationToken.None).GetAwaiter().GetResult();int miniatury=Directory.GetFiles(Path.Combine(Program.Katalog,"dane","miniatury"),"*.png").Length;
        wiersz.Sciezka=OperacjePlikowe.ZmienNazwe(obraz,"cache-po-rename.png",false);var po=Kafelki.Metadane(wiersz,CancellationToken.None).GetAwaiter().GetResult();Wymagaj(Object.ReferenceEquals(miniatura,po)&&miniatury==Directory.GetFiles(Path.Combine(Program.Katalog,"dane","miniatury"),"*.png").Length,"Zachowany cache RAM i dysku");
        wyniki.Add("Create, numerowanie, rename pliku/folderu/case, konflikty, walidacja, rozszerzenia, indeks, duplikaty, historia, cache miniatur i F5 bez hashowania: OK (wyłącznie fixture)");
        var aplikacja=new Application {ShutdownMode=ShutdownMode.OnExplicitShutdown};System.Threading.SynchronizationContext.SetSynchronizationContext(new DispatcherSynchronizationContext(Dispatcher.CurrentDispatcher));
        var okno=new OknoGlowne();try{okno.TestujOperacjeGUI(korzen,Path.Combine(katalog,"zrzuty-operacji"));okno.TestujWidoki(Path.Combine(katalog,"zrzuty-operacji"));string danePanelu=Path.Combine(katalog,"eksplorator-panel");TestyEksploratoraPanelu.Przygotuj(danePanelu,Path.Combine(katalog,"dane-testowe","album zdjęć","miniatura.png"));okno.TestujEksploratorPanel(danePanelu,Path.Combine(katalog,"zrzuty-operacji"));}catch(Exception blad){throw new InvalidOperationException(okno.DiagnostykaTestu(),blad);}okno.Okno.Close();
        wyniki.Add("Eksplorator i Panel informacji: F5 bez skanu, dane spoza indeksu, zdjęcie/EXIF, AVI, WAV, Ikony/Szczegóły, resize, multi-select, cache i anulowanie bez hashowania: OK");
        wyniki.Add("WPF widoki: zmiana widoku i zaznaczenie, kotwica skali, Ctrl+koło, wspólny suwak, limity, zapis/resize/kolejność kolumn, nagłówki, sort przed paginacją i wirtualizacja 100000 rekordów: OK");wyniki.Add("WPF: historia, skróty Alt, mysz XButton, scroll, inline create/rename, ESC, ENTER, konflikt i F5: OK");
    }
}
public sealed partial class OknoGlowne {
    void OdpowiedzNaOstrzezenie(bool zmien,string zrzut){var timer=new DispatcherTimer {Interval=TimeSpan.FromMilliseconds(30)};timer.Tick+=(s,e)=>{var dialog=Application.Current.Windows.Cast<Window>().FirstOrDefault(w=>w.Title=="Zmiana rozszerzenia");if(dialog==null)return;timer.Stop();if(zrzut!=null)Renderuj(dialog,zrzut);var przycisk=Potomkowie((DependencyObject)dialog.Content).OfType<Button>().First(w=>Convert.ToString(w.Content)==(zmien?"Zmień":"Anuluj"));przycisk.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));};timer.Start();}
    public string DiagnostykaTestu(){return "folder="+folder+" tryb="+tryb+" stan="+stan.Text+" wiersze="+String.Join(",",ostatnie.Select(w=>w.Nazwa))+" edycja="+(edycjaNazwy==null?"brak":edycjaNazwy.Text);}
    public void TestujOperacjeGUI(string korzen,string zrzuty){
        Directory.CreateDirectory(zrzuty);Okno.ShowActivated=false;Okno.ShowInTaskbar=false;Okno.Opacity=0;Okno.Show();OtworzFolder(korzen);Oczekuj(()=>ostatnie.Any(w=>w.Nazwa=="Album"));
        Kafelki.Ustawienia.Widoki[KluczWidoku()]="Lista szczegółowa";PokazWybranyWidok();Okno.UpdateLayout();
        TestyOperacji.Wymagaj(SkrotKlawisza(Key.Left,ModifierKeys.Alt,false)=="wstecz"&&SkrotKlawisza(Key.Right,ModifierKeys.Alt,false)=="dalej"&&SkrotKlawisza(Key.Up,ModifierKeys.Alt,false)=="rodzic","Skróty Alt");
        TestyOperacji.Wymagaj(SkrotKlawisza(Key.Back,ModifierKeys.None,true)==""&&SkrotKlawisza(Key.F2,ModifierKeys.None,true)==""&&SkrotKlawisza(Key.Back,ModifierKeys.None,false)=="wstecz","Ochrona edycji tekstu");
        string album=Path.Combine(korzen,"Album");WykonajSkrot("otworz");OtworzFolder(album);Oczekuj(()=>folder==album&&ostatnie.Count==1);WykonajSkrot(SkrotKlawisza(Key.Left,ModifierKeys.Alt,false));Oczekuj(()=>folder==korzen&&ostatnie.Count>=4);WykonajSkrot(SkrotKlawisza(Key.Right,ModifierKeys.Alt,false));Oczekuj(()=>folder==album&&ostatnie.Count==1);WykonajSkrot(SkrotKlawisza(Key.Up,ModifierKeys.Alt,false));Oczekuj(()=>folder==korzen&&ostatnie.Count>=4);
        foreach(MouseButton przycisk in new[]{MouseButton.XButton1,MouseButton.XButton2}){var zdarzenie=new MouseButtonEventArgs(Mouse.PrimaryDevice,Environment.TickCount,przycisk){RoutedEvent=UIElement.PreviewMouseDownEvent};Okno.RaiseEvent(zdarzenie);TestyOperacji.Wymagaj(zdarzenie.Handled,"Przechwycenie przycisku myszy");}Oczekuj(()=>folder==korzen&&ostatnie.Count>=4);
        Kontrolka<Button>("Wstecz").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Oczekuj(()=>folder==album&&ostatnie.Count==1);Kontrolka<Button>("Dalej").RaiseEvent(new RoutedEventArgs(Button.ClickEvent));Oczekuj(()=>folder==korzen&&ostatnie.Count>=4);
        Renderuj(Okno,Path.Combine(zrzuty,"11-nawigacja.png"));
        WykonajSkrot(SkrotKlawisza(Key.N,ModifierKeys.Control|ModifierKeys.Shift,false));Oczekuj(()=>edycjaNazwy!=null);Renderuj(Okno,Path.Combine(zrzuty,"12-nowy-folder-inline.png"));TestyOperacji.Wymagaj(edycjaNazwy.Text=="Nowy folder","Nowy folder edytowany inline");edycjaNazwy.Text="Utworzony w GUI";TestyOperacji.Wymagaj(ZatwierdzNazwe(),"Zatwierdzenie nowego folderu");Oczekuj(()=>ostatnie.Any(w=>w.Nazwa=="Utworzony w GUI"));Okno.UpdateLayout();
        EdytujNazwe(ostatnie.First(w=>w.Nazwa=="Utworzony w GUI"));TestyOperacji.Wymagaj(edycjaNazwy!=null,"Rename folder inline");edycjaNazwy.Text="Album";TestyOperacji.Wymagaj(!ZatwierdzNazwe()&&edycjaNazwy!=null,"Konflikt zachowuje edycję");edycjaNazwy.Text="zła?";TestyOperacji.Wymagaj(!ZatwierdzNazwe()&&edycjaNazwy!=null,"Walidacja zachowuje edycję");edycjaNazwy.Text="Folder po zmianie";TestyOperacji.Wymagaj(ZatwierdzNazwe(),"Rename folder GUI");Oczekuj(()=>ostatnie.Any(w=>w.Nazwa=="Folder po zmianie"));Okno.UpdateLayout();
        var plik=ostatnie.First(w=>w.Nazwa=="wakacje.jpg");EdytujNazwe(plik);TestyOperacji.Wymagaj(edycjaNazwy.SelectionLength==7,"Zaznaczone tylko imię pliku");Renderuj(Okno,Path.Combine(zrzuty,"13-rename-inline.png"));edycjaNazwy.Text="plik-renamed.jpg";var enter=new KeyEventArgs(Keyboard.PrimaryDevice,PresentationSource.FromVisual(Okno),Environment.TickCount,Key.Enter){RoutedEvent=UIElement.PreviewKeyDownEvent};edycjaNazwy.RaiseEvent(enter);Oczekuj(()=>edycjaNazwy==null&&ostatnie.Any(w=>w.Nazwa=="plik-renamed.jpg"));Okno.UpdateLayout();EdytujNazwe(ostatnie.First(w=>w.Nazwa=="plik-renamed.jpg"));edycjaNazwy.Text="anulowane.jpg";var esc=new KeyEventArgs(Keyboard.PrimaryDevice,PresentationSource.FromVisual(Okno),Environment.TickCount,Key.Escape){RoutedEvent=UIElement.PreviewKeyDownEvent};edycjaNazwy.RaiseEvent(esc);TestyOperacji.Wymagaj(edycjaNazwy==null&&!File.Exists(Path.Combine(korzen,"anulowane.jpg")),"ESC anuluje");
        EdytujNazwe(ostatnie.First(w=>w.Nazwa=="plik-renamed.jpg"));edycjaNazwy.Text="plik-renamed.txt";OdpowiedzNaOstrzezenie(false,Path.Combine(zrzuty,"15-ostrzezenie-rozszerzenie.png"));TestyOperacji.Wymagaj(!ZatwierdzNazwe()&&File.Exists(Path.Combine(korzen,"plik-renamed.jpg")),"Anulowanie zmiany rozszerzenia");OdpowiedzNaOstrzezenie(true,null);TestyOperacji.Wymagaj(ZatwierdzNazwe(),"Potwierdzenie zmiany rozszerzenia");Oczekuj(()=>ostatnie.Any(w=>w.Nazwa=="plik-renamed.txt"));
        Kafelki.Ustawienia.Widoki[KluczWidoku()]="Duże kafelki";PokazWybranyWidok();Okno.UpdateLayout();EdytujNazwe(ostatnie.First(w=>w.Nazwa=="plik-renamed.txt"));TestyOperacji.Wymagaj(edycjaNazwy!=null,"Edycja na kafelku");Renderuj(Okno,Path.Combine(zrzuty,"16-rename-kafelek.png"));edycjaNazwy.Text="plik-kafelek.txt";TestyOperacji.Wymagaj(ZatwierdzNazwe(),"Rename z kafelka");Oczekuj(()=>ostatnie.Any(w=>w.Nazwa=="plik-kafelek.txt"));
        File.WriteAllText(Path.Combine(korzen,"zewnetrzny-GUI.txt"),"zewnętrzny");WykonajSkrot(SkrotKlawisza(Key.F5,ModifierKeys.None,false));Oczekuj(()=>!zajety&&ostatnie.Any(w=>w.Nazwa=="zewnetrzny-GUI.txt"));
        // Wiele wierszy wyłącznie we własnym katalogu testowym zapewnia rzeczywisty scroll.
        string przewijany=Path.Combine(korzen,"scroll");Directory.CreateDirectory(przewijany);for(int i=0;i<80;i++)File.WriteAllText(Path.Combine(przewijany,"test-"+i.ToString("000")+".txt"),"test");Directory.CreateDirectory(Path.Combine(przewijany,"dziecko"));OperacjePlikowe.OdswiezFolder(przewijany);OtworzFolder(przewijany);Oczekuj(()=>ostatnie.Count>70&&!stan.Text.StartsWith("Wczytywanie"));Renderuj(Okno,Path.Combine(zrzuty,"14-scroll-przed.png"));Kafelki.Ustawienia.Widoki[KluczWidoku()]="Lista szczegółowa";PokazWybranyWidok();Okno.UpdateLayout();var scroll=ScrollWidoku();scroll.ScrollToVerticalOffset(20);Okno.UpdateLayout();double pozycja=scroll.VerticalOffset;Kafelki.Ustawienia.SkalaDuzych=125;Kafelki.Ustawienia.SkalaKompaktowych=75;TestyOperacji.Wymagaj(pozycja>0,"Rzeczywiste przewijanie");OtworzFolder(Path.Combine(przewijany,"dziecko"));Oczekuj(()=>ostatnie.Count==0);Kafelki.Ustawienia.SkalaDuzych=100;Kafelki.Ustawienia.SkalaKompaktowych=100;Historia(-1);Oczekuj(()=>ostatnie.Count>70&&!stan.Text.StartsWith("Wczytywanie"));Renderuj(Okno,Path.Combine(zrzuty,"14-scroll-po.png"));TestyOperacji.Wymagaj(Math.Abs(ScrollWidoku().VerticalOffset-pozycja)<1,"Scroll przed="+pozycja+" po="+ScrollWidoku().VerticalOffset+" zapisany="+historia.Wpisy[historia.Pozycja].Scroll);TestyOperacji.Wymagaj(wyborWidoku.SelectedItem.ToString()=="Lista szczegółowa","Tryb po powrocie");TestyOperacji.Wymagaj(Kafelki.Ustawienia.SkalaDuzych==125&&Kafelki.Ustawienia.SkalaKompaktowych==75,"Skale po powrocie");Renderuj(Okno,Path.Combine(zrzuty,"14-scroll-back.png"));
    }
}
}
