using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Threading;
using System.Windows.Media;
using System.Windows.Media.Imaging;

namespace MapaDyskow {
public static class Testy {
    [DllImport("kernel32.dll",EntryPoint="CreateHardLinkW",CharSet=CharSet.Unicode,SetLastError=true)]static extern bool UtworzHardlink(string nowa,string istniejaca,IntPtr zabezpieczenia);
    static void Wymagaj(bool warunek,string opis){if(!warunek)throw new InvalidOperationException("TEST: "+opis);}
    static void Zapisz(string sciezka,byte[] dane){using(var plik=new FileStream(sciezka,FileMode.CreateNew,FileAccess.Write))plik.Write(dane,0,dane.Length);}
    static string Skrot(string sciezka){using(var hash=SHA256.Create())using(var plik=File.OpenRead(sciezka))return BitConverter.ToString(hash.ComputeHash(plik)).Replace("-","").ToLowerInvariant();}
    public static void Uruchom(){string katalogProgramu=Program.Katalog,indeksProgramu=Program.Indeks;var wyniki=new List<string>();string katalog=Path.Combine(katalogProgramu,"testy","proba-"+DateTime.UtcNow.ToString("yyyyMMdd-HHmmss")+"-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(katalog);string aplikacja=Path.Combine(katalog,"aplikacja"),zrodla=Path.Combine(katalog,"dane-testowe"),drugi=Path.Combine(katalog,"drugi-zakres");Directory.CreateDirectory(aplikacja);Directory.CreateDirectory(zrodla);Directory.CreateDirectory(drugi);string bazaTestowa=Path.Combine(aplikacja,"indeks.sqlite");
        try{using(var oryginal=new Baza(indeksProgramu,false))using(var baza=new Baza(bazaTestowa,true))foreach(var r in oryginal.Zapytaj("SELECT sql FROM sqlite_master WHERE type IN ('table','index') AND sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY CASE type WHEN 'table' THEN 0 ELSE 1 END"))baza.Wykonaj((string)r[0]);Program.Katalog=aplikacja+Path.DirectorySeparatorChar;Program.Indeks=bazaTestowa;
            foreach(string folder in new[]{"album zdjęć","kopia","hardlink","dokumenty","pusty"})Directory.CreateDirectory(Path.Combine(zrodla,folder));
            string oryginalZdjecia=Path.Combine(zrodla,"album zdjęć","zdjęcie.jpg");Zapisz(oryginalZdjecia,Enumerable.Repeat((byte)65,1024).ToArray());Zapisz(Path.Combine(zrodla,"kopia","inna-nazwa.jpg"),Enumerable.Repeat((byte)65,1024).ToArray());Zapisz(Path.Combine(zrodla,"kopia","zdjęcie.jpg"),Enumerable.Repeat((byte)66,1024).ToArray());Wymagaj(UtworzHardlink(Path.Combine(zrodla,"hardlink","dowiazanie.jpg"),oryginalZdjecia,IntPtr.Zero),"Utworzenie testowego hardlinku: "+Marshal.GetLastWin32Error());
            Zapisz(Path.Combine(zrodla,"dokumenty","ważne.pdf"),System.Text.Encoding.UTF8.GetBytes("%PDF-1.7 przyklad"));Zapisz(Path.Combine(zrodla,"film.mp4"),System.Text.Encoding.UTF8.GetBytes("przyklad filmu testowego"));for(int i=0;i<205;i++)Zapisz(Path.Combine(zrodla,"dokumenty","dokument-"+i.ToString("000")+".txt"),Enumerable.Repeat((byte)i,30+i).ToArray());
            string obraz=Path.Combine(zrodla,"album zdjęć","miniatura.png");var miniatura=BitmapSource.Create(32,20,96,96,PixelFormats.Bgra32,null,Enumerable.Repeat((byte)125,32*20*4).ToArray(),32*4);var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(miniatura));using(var cel=new FileStream(obraz,FileMode.CreateNew,FileAccess.Write))encoder.Save(cel);
            var przed=Directory.EnumerateFiles(zrodla,"*",SearchOption.AllDirectories).ToDictionary(p=>p,p=>Tuple.Create(Skrot(p),File.GetLastWriteTimeUtc(p)));
            Skaner.Skanuj(zrodla,true,CancellationToken.None,s=>{});using(var baza=new Baza(bazaTestowa,false)){Wymagaj(Convert.ToInt64(baza.Wartosc("SELECT count(*) FROM pliki"))==212,"Pełna liczba plików");var grupa=baza.Zapytaj("SELECT lokalizacje,niezalezne,potencjal,niepewne FROM grupy_duplikatow WHERE rozmiar=1024");Wymagaj(grupa.Count==1&&Convert.ToInt64(grupa[0][0])==3&&Convert.ToInt64(grupa[0][1])==2&&Convert.ToInt64(grupa[0][2])==1024&&Convert.ToInt64(grupa[0][3])==0,"Pełny hash, różne nazwy, hardlink i jednakowa nazwa z różną treścią");Wymagaj(baza.Zapytaj("SELECT sciezka FROM pliki WHERE folder=? ORDER BY sciezka LIMIT 201",Path.Combine(zrodla,"dokumenty")).Count==201,"Stronicowanie 205 plików");}wyniki.Add("SHA-256, odmienne treści pod tą samą nazwą, hardlinki i paginacja: OK");
            var w=new Wiersz {Rodzaj="plik",Sciezka=obraz,Rozmiar=new FileInfo(obraz).Length,Zmiana=(File.GetLastWriteTimeUtc(obraz)-Program.Epoka).TotalSeconds};var meta=Kafelki.Metadane(w,CancellationToken.None).GetAwaiter().GetResult();Wymagaj(meta.Miniatura!=null&&meta.Miniatura.IsFrozen&&meta.Szerokosc==32&&meta.Wysokosc==20&&meta.Utworzenie.HasValue,"Miniatura, oryginalne wymiary, zamrożenie i rzeczywista data utworzenia");var metaDruga=Kafelki.Metadane(w,CancellationToken.None).GetAwaiter().GetResult();Wymagaj(Object.ReferenceEquals(meta,metaDruga),"Cache RAM");var anulujMiniature=new CancellationTokenSource();anulujMiniature.Cancel();bool przerwanoMiniature=false;try{Kafelki.Metadane(w,anulujMiniature.Token).GetAwaiter().GetResult();}catch(OperationCanceledException){przerwanoMiniature=true;}Wymagaj(przerwanoMiniature,"Anulowanie żądania miniatury");wyniki.Add("Miniatury, cache i anulowanie: OK");
            string nieistniejacy=Path.Combine(zrodla,"nieistniejacy-stary-wpis.txt");using(var baza=new Baza(bazaTestowa,true))baza.Wykonaj("INSERT INTO pliki(sciezka,folder,rozmiar,zmiana,typ,atrybuty,urzadzenie,tozsamosc) VALUES(?,?,999,0,'dokumenty',0,'0','0')",nieistniejacy,zrodla);Skaner.Skanuj(zrodla,true,CancellationToken.None,s=>{});using(var baza=new Baza(bazaTestowa,false))Wymagaj(Convert.ToInt64(baza.Wartosc("SELECT count(*) FROM pliki WHERE sciezka=?",nieistniejacy))==0,"Usunięcie wyłącznie nieaktualnego rekordu indeksu");
            string przedAnulowaniem;using(var baza=new Baza(bazaTestowa,false))przedAnulowaniem=Program.Json.Serialize(baza.Zapytaj("SELECT sciezka,rozmiar,sha256 FROM pliki ORDER BY sciezka"));var anuluj=new CancellationTokenSource();bool przerwano=false;try{Skaner.Skanuj(zrodla,true,anuluj.Token,s=>anuluj.Cancel());}catch(OperationCanceledException){przerwano=true;}Wymagaj(przerwano,"Anulowanie skanowania");using(var baza=new Baza(bazaTestowa,false))Wymagaj(przedAnulowaniem==Program.Json.Serialize(baza.Zapytaj("SELECT sciezka,rozmiar,sha256 FROM pliki ORDER BY sciezka")),"Rollback indeksu");wyniki.Add("Ponowny skan, nieaktualny wpis i rollback: OK");
            string oryginalDat=Path.Combine(drugi,"oryginal.dat");Zapisz(oryginalDat,Enumerable.Repeat((byte)91,333).ToArray());Skaner.Skanuj(drugi,true,CancellationToken.None,s=>{});using(var baza=new Baza(bazaTestowa,true))baza.Wykonaj("UPDATE pliki SET sha256=?,urzadzenie='0',tozsamosc='0' WHERE sciezka=?",Skrot(oryginalDat),oryginalDat);string kopiaDat=Path.Combine(zrodla,"nowa-kopia.dat");Zapisz(kopiaDat,Enumerable.Repeat((byte)91,333).ToArray());Wymagaj(UtworzHardlink(Path.Combine(zrodla,"nowy-hardlink.dat"),oryginalDat,IntPtr.Zero),"Hardlink między zakresami");Skaner.Skanuj(zrodla,true,CancellationToken.None,s=>{});using(var baza=new Baza(bazaTestowa,false)){var grupa=baza.Zapytaj("SELECT lokalizacje,niezalezne,potencjal,niepewne FROM grupy_duplikatow WHERE rozmiar=333");Wymagaj(grupa.Count==1&&Convert.ToInt64(grupa[0][0])==3&&Convert.ToInt64(grupa[0][1])==2&&Convert.ToInt64(grupa[0][2])==333&&Convert.ToInt64(grupa[0][3])==0,"Zachowany hash z nieznaną tożsamością i nowy hardlink");Wymagaj(Convert.ToInt64(baza.Wartosc("SELECT duplikaty FROM widok_folderow WHERE sciezka=?",drugi))==333,"Oznaczenie duplikatów poza odświeżanym zakresem");}wyniki.Add("Dopasowanie między zakresami i naprawa tożsamości: OK");
            string podfolder=Path.Combine(zrodla,"nowy podfolder");Directory.CreateDirectory(podfolder);Zapisz(Path.Combine(podfolder,"nowy.txt"),Enumerable.Repeat((byte)33,23).ToArray());Skaner.Skanuj(podfolder,true,CancellationToken.None,s=>{});using(var baza=new Baza(bazaTestowa,false)){Wymagaj(Convert.ToInt64(baza.Wartosc("SELECT pliki FROM widok_folderow WHERE sciezka=?",zrodla))==215,"Agregacja rodzica po częściowym skanie");Wymagaj(Convert.ToInt64(baza.Wartosc("SELECT podfoldery FROM widok_folderow WHERE sciezka=?",zrodla))==6,"Liczba podfolderów rodzica");Wymagaj(Convert.ToString(baza.Wartosc("PRAGMA quick_check"))=="ok","Integralność testowej bazy");}
            string systemowy=Path.Combine(zrodla,"AppData"),dzieckoSystemowe=Path.Combine(systemowy,"Cache");Directory.CreateDirectory(dzieckoSystemowe);Zapisz(Path.Combine(dzieckoSystemowe,"system.dat"),new byte[19]);Skaner.Skanuj(systemowy,true,CancellationToken.None,s=>{});using(var baza=new Baza(bazaTestowa,false)){Wymagaj(Convert.ToInt64(baza.Wartosc("SELECT systemowy FROM widok_folderow WHERE sciezka=?",systemowy))==1&&Convert.ToInt64(baza.Wartosc("SELECT systemowy FROM widok_folderow WHERE sciezka=?",dzieckoSystemowe))==1,"Dziedziczenie oznaczenia systemowego");}bool chroniony=false;try{Skaner.Skanuj(aplikacja,true,CancellationToken.None,s=>{});}catch(IOException){chroniony=true;}Wymagaj(chroniony,"Ochrona katalogu własnej bazy");wyniki.Add("Systemowe podfoldery i ochrona własnej bazy: OK");
            foreach(var para in przed){Wymagaj(File.Exists(para.Key)&&Skrot(para.Key)==para.Value.Item1&&File.GetLastWriteTimeUtc(para.Key)==para.Value.Item2,"Zachowanie źródła: "+para.Key);}wyniki.Add("Agregacja przodków, integralność i niezmienione źródła: OK");
            string[] rozszerzenia={"jpg","mp4","flac","pdf","xlsx","zip","exe","iso","json","nieznany"};string[] kategorie={"Zdjęcie","Film","Audio","Dokument","Arkusz","Archiwum","Program","Obraz dysku / backup","Kod / konfiguracja","Nierozpoznany"};for(int i=0;i<rozszerzenia.Length;i++)Wymagaj(Kafelki.Kategoria(new Wiersz {Rodzaj="plik",Sciezka="plik."+rozszerzenia[i]})==kategorie[i],"Rozpoznanie typu "+rozszerzenia[i]);var ustawienia=new Wyglad();ustawienia.Widoki["C:\\zdjęcia"]="Duże kafelki";ustawienia.Widoki["D:\\archiwum"]="Lista szczegółowa";ustawienia.Profile["Film"].Padding=18;ustawienia.SkalaDuzych=125;ustawienia.SkalaKompaktowych=75;var odczyt=Program.Json.Deserialize<Wyglad>(Program.Json.Serialize(ustawienia));Wymagaj(odczyt.Widoki.Count==2&&odczyt.Widoki["D:\\archiwum"]=="Lista szczegółowa"&&odczyt.Profile["Film"].Padding==18&&odczyt.SkalaDuzych==125&&odczyt.SkalaKompaktowych==75,"Trwałość trybów folderów i profili");Wymagaj(Program.Json.Deserialize<Wyglad>("{}").SkalaDuzych==100,"Domyślna skala dawnych ustawień");wyniki.Add("Kategorie, skale i serializacja personalizacji: OK");
            TestyWidokow.Uruchom(wyniki);TestyOperacji.Uruchom(katalog,wyniki);Zapisz(Path.Combine(katalog,"wynik.json"),System.Text.Encoding.UTF8.GetBytes(Program.Json.Serialize(new {sukces=true,testy=wyniki,baza=bazaTestowa})));File.WriteAllText(Path.Combine(katalogProgramu,"ostatni-test.json"),Program.Json.Serialize(new {sukces=true,katalog=katalog,testy=wyniki}));
        }catch(Exception blad){File.WriteAllText(Path.Combine(katalog,"blad-testu.txt"),blad.ToString());throw;}finally{Program.Katalog=katalogProgramu;Program.Indeks=indeksProgramu;}
    }
}
}
