using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;

namespace MapaDyskow {
public sealed class OknoWygladu {
    public Window Okno;StackPanel formularz;WrapPanel podglad;string wybranyProfil="Wspólny";Action odswiez;bool budowanie;ComboBox wyborPresetu;
    readonly System.Windows.Media.Imaging.BitmapSource przykladoweZdjecie=UtworzPrzyklad();
    static System.Windows.Media.Imaging.BitmapSource UtworzPrzyklad(){const int szerokosc=192,wysokosc=128;var piksele=new byte[szerokosc*wysokosc*4];for(int y=0;y<wysokosc;y++)for(int x=0;x<szerokosc;x++){int i=(y*szerokosc+x)*4;bool gora=y>75+Math.Abs(x-60)/4;bool slonce=(x-143)*(x-143)+(y-29)*(y-29)<150;piksele[i]=(byte)(slonce?166:gora?102:174);piksele[i+1]=(byte)(slonce?209:gora?141:134);piksele[i+2]=(byte)(slonce?229:gora?86:93);piksele[i+3]=255;}var obraz=System.Windows.Media.Imaging.BitmapSource.Create(szerokosc,wysokosc,96,96,PixelFormats.Bgra32,null,piksele,szerokosc*4);obraz.Freeze();return obraz;}
    ProfilPlytki Profil {get{return wybranyProfil=="Wspólny"?Kafelki.Ustawienia.Wspolny:Kafelki.Ustawienia.Profile[wybranyProfil];}}
    public OknoWygladu(Window wlasciciel,Action aktualizuj,bool testowy=false){odswiez=aktualizuj;Okno=new Window {Owner=wlasciciel,Title="Wygląd i personalizacja",Width=1170,Height=840,MinWidth=1000,MinHeight=650,Background=Program.Kolor("#11151D"),Foreground=Brushes.White,FontFamily=new FontFamily("Segoe UI"),WindowStartupLocation=WindowStartupLocation.CenterOwner};Okno.Resources=Program.Zasoby;var uklad=new Grid {Margin=new Thickness(22)};uklad.ColumnDefinitions.Add(new ColumnDefinition {Width=new GridLength(430)});uklad.ColumnDefinitions.Add(new ColumnDefinition());Okno.Content=uklad;formularz=new StackPanel {Margin=new Thickness(0,0,18,0)};uklad.Children.Add(new ScrollViewer {Content=formularz,VerticalScrollBarVisibility=ScrollBarVisibility.Auto});var prawa=new Grid {Margin=new Thickness(12,0,0,0)};prawa.RowDefinitions.Add(new RowDefinition {Height=GridLength.Auto});prawa.RowDefinitions.Add(new RowDefinition());prawa.RowDefinitions.Add(new RowDefinition {Height=GridLength.Auto});Grid.SetColumn(prawa,1);uklad.Children.Add(prawa);prawa.Children.Add(Program.Tekst("PODGLĄD NA ŻYWO · ELEMENTY PRZYKŁADOWE",13,"#A9BAD2"));podglad=new WrapPanel();var przewijanie=new ScrollViewer {Content=podglad,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};Grid.SetRow(przewijanie,1);prawa.Children.Add(przewijanie);var opis=Program.Tekst("Materiał szkła jest lekką imitacją. Rozmycie steruje matowością i rozproszeniem refleksu; nie uruchamia kosztownego blur dla każdego elementu. Miniatury zachowują proporcje. Zmiany zapisują się w wyglad.json.",12,"#94A6C1");Grid.SetRow(opis,2);prawa.Children.Add(opis);Okno.Closed+=(s,e)=>{if(testowy)return;try{Kafelki.Zapisz();odswiez();}catch(Exception blad){MessageBox.Show(blad.Message,"Zapisywanie wyglądu");}};Zbuduj();}
    void Zmien(){if(budowanie)return;Kafelki.Ustawienia.Preset="Custom";if(wyborPresetu!=null){budowanie=true;wyborPresetu.SelectedItem="Custom";budowanie=false;}OdswiezPodglad();}
    void Naglowek(string tekst){formularz.Children.Add(Program.Tekst(tekst,17,"#E4ECF8"));}
    void Opcje(string nazwa,string[] opcje,string wartosc,Action<string> ustaw){formularz.Children.Add(Program.Tekst(nazwa,12,"#9CB0CA"));var wybor=new ComboBox {ItemsSource=opcje,SelectedItem=wartosc,Margin=new Thickness(0,2,0,10)};wybor.SelectionChanged+=(s,e)=>{if(!budowanie&&wybor.SelectedItem!=null){ustaw(Convert.ToString(wybor.SelectedItem));if(nazwa!="Preset"&&nazwa!="Edytowany profil")Zmien();else OdswiezPodglad();}};if(nazwa=="Preset")wyborPresetu=wybor;formularz.Children.Add(wybor);}
    void Przelacz(string nazwa,bool wartosc,Action<bool> ustaw){var pole=new CheckBox {Content=nazwa,IsChecked=wartosc,Margin=new Thickness(0,8,0,8)};pole.Click+=(s,e)=>{ustaw(pole.IsChecked==true);Zmien();};formularz.Children.Add(pole);}
    void Suwak(string nazwa,double min,double max,double wartosc,Action<double> ustaw){var opis=Program.Tekst(nazwa+" · "+wartosc.ToString("0"),12,"#9CB0CA");formularz.Children.Add(opis);var suwak=new Slider {Minimum=min,Maximum=max,Value=wartosc,TickFrequency=1,IsSnapToTickEnabled=true,Margin=new Thickness(0,2,0,12)};suwak.ValueChanged+=(s,e)=>{if(budowanie)return;opis.Text=nazwa+" · "+e.NewValue.ToString("0");ustaw(e.NewValue);Zmien();};formularz.Children.Add(suwak);}
    void Kolor(string nazwa,string wartosc,Action<string> ustaw){formularz.Children.Add(Program.Tekst(nazwa+" · HEX / RGB",12,"#9CB0CA"));var panel=new StackPanel();var wiersz=new WrapPanel();panel.Children.Add(wiersz);var hex=new TextBox {Text=wartosc,Width=118,Margin=new Thickness(0,0,6,5)};wiersz.Children.Add(hex);var rgb=new TextBox {Width=155,Margin=new Thickness(0,0,6,5)};wiersz.Children.Add(rgb);var probka=new Border {Width=22,Height=22,Background=new SolidColorBrush(Kafelki.Odcien(wartosc)),Margin=new Thickness(2)};wiersz.Children.Add(probka);Color kolor=Kafelki.Odcien(wartosc);rgb.Text=kolor.R+", "+kolor.G+", "+kolor.B;bool zmiana=false;
        Action<Color> przyjmij=c=>{if(zmiana)return;int pozycjaHex=hex.CaretIndex,pozycjaRgb=rgb.CaretIndex;zmiana=true;hex.Text="#"+c.R.ToString("X2")+c.G.ToString("X2")+c.B.ToString("X2");rgb.Text=c.R+", "+c.G+", "+c.B;hex.CaretIndex=Math.Min(pozycjaHex,hex.Text.Length);rgb.CaretIndex=Math.Min(pozycjaRgb,rgb.Text.Length);probka.Background=new SolidColorBrush(c);hex.ToolTip=null;rgb.ToolTip=null;ustaw(hex.Text);zmiana=false;Zmien();};
        hex.TextChanged+=(s,e)=>{if(zmiana||budowanie)return;try{if(hex.Text.Length!=7||!hex.Text.StartsWith("#"))return;przyjmij((Color)ColorConverter.ConvertFromString(hex.Text));}catch{hex.ToolTip="Wpisz HEX, np. #D6A84B";}};
        rgb.TextChanged+=(s,e)=>{if(zmiana||budowanie)return;try{string[] czesci=rgb.Text.Split(',');if(czesci.Length==3)przyjmij(Color.FromRgb(byte.Parse(czesci[0].Trim()),byte.Parse(czesci[1].Trim()),byte.Parse(czesci[2].Trim())));}catch{rgb.ToolTip="RGB: trzy liczby 0–255, oddzielone przecinkami";}};
        wiersz.Children.Add(Program.Przycisk("Wybierz…",()=>{Color obecny=Kafelki.Odcien(hex.Text);using(var dialog=new System.Windows.Forms.ColorDialog {FullOpen=true,Color=System.Drawing.Color.FromArgb(obecny.R,obecny.G,obecny.B)})if(dialog.ShowDialog()==System.Windows.Forms.DialogResult.OK)przyjmij(Color.FromRgb(dialog.Color.R,dialog.Color.G,dialog.Color.B));}));formularz.Children.Add(panel);}
    void Zbuduj(){budowanie=true;formularz.Children.Clear();var u=Kafelki.Ustawienia;if(u.OsobneProfile&&!u.Profile.ContainsKey(wybranyProfil))wybranyProfil="Folder";Naglowek("Wygląd i personalizacja");Opcje("Preset",new[]{"Windows Fluent","Liquid Glass","Matte Glass","Minimal","Colorful","Custom"},u.Preset,n=>{ZastosujPreset(n);Zbuduj();});formularz.Children.Add(Program.Przycisk("Przywróć domyślne",()=>{var widoki=u.Widoki;Kafelki.Ustawienia=new Wyglad {Widoki=widoki,UkladyFolderow=u.UkladyFolderow,Kolumny=u.Kolumny,FolderyNaPoczatku=u.FolderyNaPoczatku,PanelSzczegolow=u.PanelSzczegolow};wybranyProfil="Wspólny";Zbuduj();}));
        formularz.Children.Add(Program.Przycisk("Zastosuj i zapisz",()=>{try{Kafelki.Zapisz();odswiez();}catch(Exception blad){MessageBox.Show(blad.Message,"Zapisywanie wyglądu");}}));Naglowek("Kolor folderów");Opcje("Tryb",new[]{"Systemowy / domyślny","Jeden własny kolor","Według kategorii","Według tagów","Według zawartości"},u.TrybFolderow,n=>{u.TrybFolderow=n;Zbuduj();});Kolor("Własny kolor folderów",u.KolorFolderow,c=>u.KolorFolderow=c);
        if(u.TrybFolderow=="Według kategorii")foreach(string typ in u.KoloryKategorii.Keys.ToArray()){string t=typ;Kolor(t,u.KoloryKategorii[t],c=>u.KoloryKategorii[t]=c);}if(u.TrybFolderow=="Według tagów")foreach(string tag in u.KoloryTagow.Keys.ToArray()){string t=tag;Kolor(t,u.KoloryTagow[t],c=>u.KoloryTagow[t]=c);}
        Naglowek("Płytka pod ikoną");Przelacz("Osobne profile według typu",u.OsobneProfile,v=>{u.OsobneProfile=v;wybranyProfil=v?"Folder":"Wspólny";if(v&&!u.ProfileZainicjalizowane){foreach(string typ in u.Profile.Keys.ToArray())u.Profile[typ]=Program.Json.Deserialize<ProfilPlytki>(Program.Json.Serialize(u.Wspolny));u.ProfileZainicjalizowane=true;}Zbuduj();});Opcje("Edytowany profil",u.OsobneProfile?new[]{"Folder","Film","Zdjęcie","Dokument","Archiwum","Audio","System"}:new[]{"Wspólny"},u.OsobneProfile?wybranyProfil:"Wspólny",n=>{wybranyProfil=n;Zbuduj();});if(!u.OsobneProfile)wybranyProfil="Wspólny";var p=Profil;
        Przelacz("Płytka pod ikoną — ON / OFF",p.Wlaczona,v=>p.Wlaczona=v);Suwak("Przezroczystość (%)",0,100,p.Przezroczystosc,v=>p.Przezroczystosc=v);Suwak("Rozmycie / matowość materiału (%)",0,100,p.Rozmycie,v=>p.Rozmycie=v);Suwak("Zaokrąglenie (px)",0,30,p.Zaokraglenie,v=>p.Zaokraglenie=v);Suwak("Rozmiar płytki (px)",70,148,p.Rozmiar,v=>p.Rozmiar=v);Suwak("Odstęp ikony (px)",6,24,p.Padding,v=>p.Padding=v);Suwak("Rozmiar ikony (%)",60,90,p.Ikona,v=>p.Ikona=v);
        Opcje("Kolor szklanej płytki",new[]{"Automatyczny","Zależny od typu pliku","Zależny od koloru folderu","Jeden własny kolor","Neutralny","Przezroczysty"},p.TrybKoloru,n=>p.TrybKoloru=n);Kolor("Kolor płytki",p.Kolor,c=>p.Kolor=c);
        Opcje("Obramowanie płytki",new[]{"Wyłączone","Subtelne","Standardowe"},p.Obramowanie,n=>p.Obramowanie=n);Kolor("Kolor obramowania",p.KolorObramowania,c=>p.KolorObramowania=c);Suwak("Przezroczystość obramowania (%)",0,100,100-p.AlfaObramowania,v=>p.AlfaObramowania=100-v);Suwak("Grubość obramowania (px)",0,3,p.Grubosc,v=>p.Grubosc=v);
        Opcje("Efekt szkła",new[]{"Wyłączony","Minimalny","Subtelny","Standardowy","Mocny"},p.Szklo,n=>p.Szklo=n);Opcje("Refleks światła",new[]{"OFF","Subtelny","DYNAMICZNY"},p.Refleks,n=>p.Refleks=n);Opcje("Kształt płytki",new[]{"Lekko zaokrąglony","Bardziej zaokrąglony","Squircle","Prawie okrągły"},p.Ksztalt,n=>p.Ksztalt=n);Przelacz("Miniatura w szklanej ramce",p.RamkaMiniatury,v=>p.RamkaMiniatury=v);budowanie=false;OdswiezPodglad();}
    void ZastosujPreset(string nazwa){var u=Kafelki.Ustawienia;var widoki=u.Widoki;if(nazwa=="Custom"){u.Preset=nazwa;return;}Kafelki.Ustawienia=new Wyglad {Widoki=widoki,Preset=nazwa};u=Kafelki.Ustawienia;wybranyProfil="Wspólny";var p=u.Wspolny;switch(nazwa){case "Liquid Glass":p.Przezroczystosc=80;p.Rozmycie=35;p.Refleks="DYNAMICZNY";p.Szklo="Standardowy";p.Zaokraglenie=22;break;case "Matte Glass":p.Przezroczystosc=45;p.Rozmycie=70;p.Refleks="OFF";break;case "Minimal":p.Wlaczona=false;p.Szklo="Wyłączony";p.Refleks="OFF";break;case "Colorful":u.TrybFolderow="Według kategorii";p.TrybKoloru="Zależny od typu pliku";p.Przezroczystosc=65;break;}}
    void OdswiezPodglad(){podglad.Children.Clear();var folder=new Wiersz {Przyklad=true,Rodzaj="folder",Nazwa="Zgranie telefonu 2023",Sciezka="Przykład folderu",Rozmiar=67323576320L,Pliki=4281,Podfoldery=173,Oznaczenia="ZGRYW TELEFONU · DO PRZEJRZENIA",Zmiana=1718640000};folder.Typy[1]=folder.Rozmiar;var przyklady=new List<Wiersz>{folder};foreach(string nazwa in new[]{"wakacje_trzebiatow_01.mp4","IMG_20250802_173455.jpg","Dokument.pdf","Archiwum.zip"})przyklady.Add(new Wiersz {Przyklad=true,Rodzaj="plik",Nazwa=nazwa,Sciezka=nazwa,Rozmiar=8421376,Utworzenie=new DateTime(2024,6,18),Zmiana=1718640000,Oznaczenia="Przykład"});if(wybranyProfil=="Audio")przyklady.Add(new Wiersz {Przyklad=true,Rodzaj="plik",Nazwa="Muzyka.flac",Sciezka="Muzyka.flac",Rozmiar=82000000});if(wybranyProfil=="System")przyklady.Add(new Wiersz {Przyklad=true,Rodzaj="folder",Systemowy=true,Nazwa="Folder systemowy",Sciezka="Przykład systemowy",Rozmiar=-1,Pliki=-1,Podfoldery=-1,Oznaczenia="SYSTEMOWY — NIE RUSZAĆ"});foreach(var w in przyklady){if(Kafelki.Kategoria(w)=="Zdjęcie")w.PrzykladowaMiniatura=przykladoweZdjecie;var kafelek=Kafelki.Utworz(w,true,p=>{},p=>{},p=>{},p=>false);podglad.Children.Add(kafelek);}}
}
}
